import type { ModuleDocs } from '../../docs/spec.js';
import { DOC_TAGS } from '../../docs/tags.js';

export const salesDocs: ModuleDocs = {
  tag: DOC_TAGS.sales,
  description:
    'The Sales workspace (**R112**): internal Sales Representatives onboard dealerships with ' +
    'the dealer, in person. Every route needs an Admin Member session whose role holds ' +
    '`sales:workspace` (SALES_REP); console roles are refused at the mount with ' +
    '`SALES_WORKSPACE_FORBIDDEN`, and a Sales Representative is refused the admin console.\n\n' +
    'Every dealership route is scoped to the dealerships this member assisted; any other id ' +
    'is a 404. The dealership created is an ordinary one — the same row, the same review ' +
    'lifecycle, the same notifications — with its provenance recorded.',
  operations: [
    {
      method: 'get',
      path: '/v1/sales/dashboard',
      operationId: 'getSalesDashboard',
      tag: DOC_TAGS.sales,
      summary: "The Sales Representative's dashboard",
      description:
        'Counts for the dealerships this member assisted \u2014 onboarded (including any since rejected), pending verification, approved \u2014 and the listing drafts, reviews and live cars across them, plus the five most recent dealerships.',
      audience: 'admin',
      permission: 'sales:dealer:read',
      responses: [{ status: 200, description: 'The dashboard.', schema: 'SalesDashboard' }],
      errors: [401, 403],
    },
    {
      method: 'get',
      path: '/v1/sales/phone/widget',
      operationId: 'getSalesPhoneWidget',
      tag: DOC_TAGS.sales,
      summary: 'OTP widget configuration for the dealer-phone step',
      description:
        'The same public widget settings the dealer’s own step 1 receives (never the provider auth key), for a Sales session.',
      audience: 'admin',
      permission: 'sales:dealer:create',
      responses: [{ status: 200, description: 'The widget settings.', schema: 'PhoneOtpWidget' }],
      errors: [401, 403],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers/phone/verify',
      operationId: 'verifyAssistedDealerPhone',
      tag: DOC_TAGS.sales,
      summary: "Verify a dealer's mobile number by OTP",
      description:
        "The dealer receives the code on their own handset and reads it out; the representative enters it and the browser exchanges it for a provider token, which is verified here server-side. Requires `consent: true` \u2014 the dealer's agreement, given by sharing the code. Answers a single-use `phoneTicket` (30 minutes) bound to this member and number; nothing is created yet. A number that already belongs to an open dealership, or to a member of one, is a **409** `DEALER_PHONE_TAKEN`. Rate-limited per member. The code itself never reaches the API and is never logged.",
      audience: 'admin',
      permission: 'sales:dealer:create',
      requestBody: {
        schema: 'SalesPhoneVerifyInput',
        description: "The number, the provider token and the dealer's consent.",
        example: { phone: '9840012345', accessToken: '<provider token>', consent: true },
      },
      responses: [
        {
          status: 200,
          description: 'Verified; ticket issued.',
          schema: 'SalesPhoneVerifyResponse',
        },
      ],
      errors: [400, 401, 403, 409, 422, 429, 503],
    },
    {
      method: 'get',
      path: '/v1/sales/dealers',
      operationId: 'listAssistedDealers',
      tag: DOC_TAGS.sales,
      summary: 'My dealerships',
      description:
        'Only dealerships this member assisted (`assistedByMemberId`), newest first, optionally by `status`; `counts` per status.',
      audience: 'admin',
      permission: 'sales:dealer:read',
      query: 'SalesDealersQuery',
      responses: [
        { status: 200, description: 'Your dealerships.', schema: 'SalesDealersResponse' },
      ],
      errors: [400, 401, 403],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers',
      operationId: 'createAssistedDealer',
      tag: DOC_TAGS.sales,
      summary: 'Start an assisted dealership',
      description:
        "Redeems the `phoneTicket` (once) and creates the dealership as a `DRAFT` with `onboardingSource: ASSISTED`, the phone verified and the consent time recorded. The email is stored **unverified** \u2014 it never becomes a sign-in identity until the dealer proves it. Same business-field rules as the dealer's own onboarding; same name-per-city and GSTIN/PAN uniqueness.",
      audience: 'admin',
      permission: 'sales:dealer:create',
      requestBody: {
        schema: 'CreateAssistedDealerInput',
        description: 'The ticket, the contact and the business details.',
      },
      responses: [{ status: 201, description: 'Created.', schema: 'SalesDealerDetail' }],
      errors: [400, 401, 403, 409, 422],
    },
    {
      method: 'get',
      path: '/v1/sales/dealers/:id',
      operationId: 'getAssistedDealer',
      tag: DOC_TAGS.sales,
      summary: 'One assisted dealership',
      description:
        'Details, completeness, documents and yard photo. A dealership this member did not assist is a **404**, never a 403 \u2014 its existence is not confirmed.',
      audience: 'admin',
      permission: 'sales:dealer:read',
      params: 'IdParam',
      responses: [{ status: 200, description: 'The dealership.', schema: 'SalesDealerDetail' }],
      errors: [400, 401, 403, 404],
    },
    {
      method: 'patch',
      path: '/v1/sales/dealers/:id',
      operationId: 'updateAssistedDealer',
      tag: DOC_TAGS.sales,
      summary: 'Edit an assisted draft',
      description:
        'While `DRAFT` and not yet claimed by the dealer. The phone cannot be changed here. Changing the email clears its verification.',
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'IdParam',
      requestBody: {
        schema: 'UpdateAssistedDealerInput',
        description: 'Any subset of the fields.',
        example: { tagline: 'Family-run since 1998, hatchbacks under \u20b96 lakh.' },
      },
      responses: [{ status: 200, description: 'Updated.', schema: 'SalesDealerDetail' }],
      errors: [400, 401, 403, 404, 409],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers/:id/email-verification',
      operationId: 'resendAssistedDealerEmailVerification',
      tag: DOC_TAGS.sales,
      summary: 'Send the dealer a new verification link',
      description:
        'Supersedes every earlier link and emails a new one to the dealership’s current address (**R113**). A link is also sent automatically when the dealership is created and whenever its email changes. Refused within a minute of the previous one (`409 VERIFICATION_COOLDOWN`) and once the dealer has claimed the dealership (`409 VERIFICATION_NOT_EDITABLE`). The representative never sees the link.',
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'IdParam',
      responses: [{ status: 200, description: 'Queued.', schema: 'SalesDealerDetail' }],
      errors: [400, 401, 403, 404, 409],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers/:id/documents/presign',
      operationId: 'presignAssistedDealerDocument',
      tag: DOC_TAGS.sales,
      summary: 'Presign a KYC document upload',
      description:
        "The same private upload path as the dealer's own onboarding, scoped to an assisted draft.",
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'IdParam',
      requestBody: { schema: 'DocumentPresignInput', description: 'The document type and file.' },
      responses: [{ status: 201, description: 'A presigned PUT.', schema: 'PresignResponse' }],
      errors: [400, 401, 403, 404, 409],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers/:id/documents/:type/commit',
      operationId: 'commitAssistedDealerDocument',
      tag: DOC_TAGS.sales,
      summary: 'Commit an uploaded KYC document',
      description: 'Confirms the object exists and marks the document uploaded.',
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'SalesDealerDocParam',
      requestBody: {
        schema: 'DocumentCommitInput',
        description: 'The document id from the presign.',
      },
      responses: [{ status: 200, description: 'Committed.', schema: 'DealerDocumentDto' }],
      errors: [400, 401, 403, 404, 409, 422],
    },
    {
      method: 'delete',
      path: '/v1/sales/dealers/:id/documents/:type',
      operationId: 'deleteAssistedDealerDocument',
      tag: DOC_TAGS.sales,
      summary: 'Remove a KYC document',
      description: 'While the draft is editable.',
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'SalesDealerDocParam',
      responses: [{ status: 204, description: 'Removed.' }],
      errors: [400, 401, 403, 404, 409],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers/:id/yard-photo/presign',
      operationId: 'presignAssistedDealerYardPhoto',
      tag: DOC_TAGS.sales,
      summary: 'Presign the yard photograph',
      description: 'The yard photograph for an assisted draft, through the same upload path.',
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'IdParam',
      requestBody: { schema: 'YardPhotoPresignInput', description: 'The image.' },
      responses: [{ status: 201, description: 'A presigned PUT.', schema: 'PresignResponse' }],
      errors: [400, 401, 403, 404, 409],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers/:id/yard-photo/commit',
      operationId: 'commitAssistedDealerYardPhoto',
      tag: DOC_TAGS.sales,
      summary: 'Commit the yard photograph',
      description: 'Confirms the uploaded image and sets it as the yard photograph.',
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'IdParam',
      requestBody: {
        schema: 'YardPhotoCommitInput',
        description: 'The media id from the presign.',
      },
      responses: [{ status: 200, description: 'Committed.', schema: 'YardPhotoDto' }],
      errors: [400, 401, 403, 404, 409, 422],
    },
    {
      method: 'delete',
      path: '/v1/sales/dealers/:id/yard-photo',
      operationId: 'deleteAssistedDealerYardPhoto',
      tag: DOC_TAGS.sales,
      summary: 'Remove the yard photograph',
      description: 'While the draft is editable.',
      audience: 'admin',
      permission: 'sales:dealer:edit',
      params: 'IdParam',
      responses: [{ status: 204, description: 'Removed.' }],
      errors: [400, 401, 403, 404, 409],
    },
    {
      method: 'post',
      path: '/v1/sales/dealers/:id/submit',
      operationId: 'submitAssistedDealer',
      tag: DOC_TAGS.sales,
      summary: 'Submit for verification',
      description:
        "Moves the draft to `PENDING_APPROVAL` through the **same** submission the dealer's own onboarding uses: the same completeness rules, the same `DealerApplied` event (and so the same emails), audited as `dealer.submitted` with this member as actor. The member cannot approve it \u2014 no Sales role holds a reviewer permission, and a reviewer who assisted a dealership is refused its decisions.",
      audience: 'admin',
      permission: 'sales:dealer:submit',
      params: 'IdParam',
      responses: [{ status: 200, description: 'Submitted.', schema: 'DealerSubmitResponse' }],
      errors: [400, 401, 403, 404, 409, 422],
    },
  ],
};
