"""Independent owner workbook: executable journeys plus one ticket per canonical ID."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
rows = json.loads((ROOT / 'registry.json').read_text())
by_id = {r['id']: r for r in rows}
out = ['# Independent product-owner UAT — all results PENDING', '',
       'Baseline `d6ae115359c4d0ae7ab0fd5115336291666cbb08`. **NO GO remains in force.** The agent has not signed off on your behalf. Perform these tests independently and record PASS/FAIL, actual outcome, timestamp, browser/device and screenshots. A blocked agent case does not become PASS through these instructions.', '',
       '## Setup before you begin', '',
       'A QA operator must provide an accessible isolated pre-production URL for this SHA, a working configured OTP channel, Google test identities, mail inbox and disposable DB/storage. The current loopback cloud runtime is not a publicly accessible owner UAT deployment. Until those prerequisites exist, affected human results remain PENDING; do not use the live production site.', '',
       'Use separate browser profiles labelled Customer A, Customer B, Dealer A OWNER, Dealer A MANAGER, Dealer A STAFF, Dealer B OWNER and Admin. A person account uses the normal Login link and verified phone. Admin uses the Admin Google login. QA supplies fictional phones/credentials privately; no credential belongs in this workbook.', '',
       'Prepare dealer A and B as approved ACTIVE, one incomplete DRAFT dealer with its document checklist still REQUIRED, a PENDING_APPROVAL dealer, and listings labelled ACTIVE-A, ACTIVE-B, RESERVED-A, SOLD-A, WITHDRAWN-A, DRAFT-A, REVIEW-A, REJECTED-A and CHANGES-A. Each published fixture needs six non-sensitive images. Prepare an existing customer invitation, a new-phone invitation, expired/revoked invitations, saved cars and enquiry histories. Supply resource IDs, public slugs and expected counts on a private fixture sheet. Reset disposable fixtures between destructive cases. Never include real KYC/customer documents.', '',
       'For direct API checks, QA supplies an authenticated Postman collection/environment with the same identities and private variables `dealerAId`, `dealerBId`, `vehicleAId`, `vehicleBId`, `listingAId`, `enquiryAId`, `enquiryBId`, `membershipAId`, `invitationId`. In requests below replace braces with fixture-sheet IDs. Use the profile specified for each request. No source-code inspection is needed. A permission button being hidden is insufficient: also send the documented API request. Clear auth before anonymous tests.', '',
       'Run the journeys below first on desktop, then repeat the customer search/save/enquiry, dealer dashboard/draft/enquiries/Team and Admin views on a real Android/iPhone/tablet as available. Test the actual keyboard, portrait/landscape, browser back and refresh. Do not substitute viewport screenshots for real-device checks.', '',
       '## Priority journeys', '']

journeys = [
('New and existing customer login', 'AUTH-001 AUTH-002 AUTH-003 AUTH-004 AUTH-005 AUTH-006 AUTH-007 AUTH-008 AUTH-009 AUTH-010 AUTH-011 AUTH-012 AUTH-013 AUTH-015 CUSTOMER-001 CUSTOMER-004', 'Customer A, a second new fictional phone, an incorrect code, an expired proof and a used proof prepared by QA; production-like HTTPS cookies.', ['From homepage select Login, enter the new phone and select Send OTP.', 'Enter the delivered code, select Verify and sign in, enter a name if asked and select Create account. Confirm the avatar/menu identifies that human.', 'Logout, repeat login with that same phone and confirm no name/signup step or duplicate account.', 'In fresh attempts enter the incorrect and expired codes; try a previously used proof in the supplied API collection. Expect refusal and no new authenticated session.', 'Request/resend or submit repeatedly up to the documented limits; observe the limit message and recovery window. QA disables the provider for one attempt; expect recoverable error, not account creation.', 'Refresh during verification; use two tabs with different in-progress phones and prove the authenticated identity matches the successfully verified number.', 'Logout and request a private page/API with the old cookie. Ask QA to expire a session and repeat. If logout-all is supported, invoke it and test another active profile; otherwise record a blocked product-policy decision.', 'On HTTPS inspect cookie attributes in browser Application/Storage: HttpOnly, Secure and intended SameSite/path/domain; do not copy its value.'], 'Correct identity; reusable existing account; invalid/expired/used proofs refused; limits and failure recovery work; old/expired sessions lose protected access.'),
('Saved cars and customer account', 'SAVED-001 SAVED-002 SAVED-003 SAVED-004 SAVED-005 SAVED-006 SAVED-007 SAVED-008 SAVED-009 SAVED-010 CUSTOMER-002 CUSTOMER-003 CUSTOMER-005 CUSTOMER-006 CUSTOMER-007 CUSTOMER-008 CUSTOMER-009 CUSTOMER-010', 'Customer A/B; ACTIVE-B saved by A; lifecycle variants on fixture sheet.', ['As anonymous visitor press the save heart on ACTIVE-B and confirm the intended login return path.', 'As Customer A save ACTIVE-B; open Saved cars from account menu and verify the same car. Remove it, verify removal, then save again and double-click.', 'Logout and log in again through normal OTP. Saved car and personal My enquiries remain present.', 'As Dealer B OWNER move that saved listing through RESERVED, SOLD or WITHDRAWN in separate reset runs. Refresh A’s Saved cars and My enquiries: clear unavailable/history behavior, no broken page or deleted history.', 'Make A a dealer member; later remove membership and suspend the employer in separate runs. Confirm A can still use Saved cars and My enquiries.', 'As Customer B, attempt A’s saved/enquiry identifiers in the supplied API collection; B must not read or mutate A’s data.'], 'Human-owned saved/history records persist through lifecycle and employer changes; duplicate save is one row; customers remain isolated.'),
('Complete dealer onboarding', 'ONBOARD-001 ONBOARD-002 ONBOARD-003 ONBOARD-004 ONBOARD-005 ONBOARD-006 ONBOARD-007 ONBOARD-008 ONBOARD-009 ONBOARD-010 ONBOARD-011 ONBOARD-012 ONBOARD-013 ONBOARD-014 ONBOARD-015 ONBOARD-016 ONBOARD-017 ONBOARD-018', 'A new eligible person, a partly completed dealer draft, required fixture documents and Google test identity.', ['Use the offered dealer onboarding entry and normal required identity/phone/Google linking steps. Confirm the same human account is reused.', 'Complete required business name, address/district/map, description/services and contact fields. Leave each required field blank once and try Continue/submit; the server must refuse it.', 'Upload each required document to its named checklist slot. Try a wrong file type and an oversized file; expect refusal. Keep all uploads fictional.', 'Refresh partway, logout/login and reopen onboarding; persisted fields/documents remain associated with that draft.', 'Submit the completed application twice rapidly; one dealership/application should exist in the review state.', 'Using Dealer B identity, request A’s document/upload IDs from the collection; expect denial. Using the applicant identity, attempt Admin approval and public listing submission; expect denial.', 'As Admin inspect this submitted application, comparing owner, contact, business fields and document slots to the fixture sheet.'], 'One correctly linked human/dealer, resumable draft, enforced required data, private correct documents, non-public unapproved dealer and correct review state.'),
('Dealer review, incomplete approval, rejection and audit', 'VERIFY-001 VERIFY-002 VERIFY-003 VERIFY-004 VERIFY-005 VERIFY-006 VERIFY-007 VERIFY-008 VERIFY-009 VERIFY-010 VERIFY-011 VERIFY-012 VERIFY-013 VERIFY-014 ADMIN-DEALER-002 ADMIN-DEALER-003 ADMIN-DEALER-004 ADMIN-DEALER-005', 'Admin; one complete submitted application and one incomplete DRAFT dealer. Disposable rejection/remediation fixture.', ['Open Admin → Dealers and inspect the submitted application and documents.', 'Approve the complete submitted application. Reopen its dealer profile/session and verify ACTIVE plus only intended permissions.', 'For the incomplete DRAFT fixture, send Admin POST /v1/admin/dealers/{dealerId}/approve with {} before documents are uploaded. Inspect status in Admin and dealer account. This is the known BUG-002 reproduction; activation is FAIL.', 'In a separate fixture, reject with a meaningful reason; verify the application’s documented purge/remediation behavior. Distinguish final rejection from Request changes.', 'For Request changes, correct the named fields/documents, resubmit and inspect the new review state. If the requested rejected resubmission policy is undefined, record the policy question instead of a pass.', 'In two Admin profiles submit conflicting review decisions together. Ask QA for the recorded DB/audit outcome; one valid final state and attributable audit trail are required.'], 'Only complete eligible applications activate; invalid/concurrent review cannot bypass verification; supported remediation and audit remain consistent.'),
('Roles, drafts and listing moderation', 'LISTING-CREATE-001 LISTING-CREATE-002 LISTING-CREATE-003 LISTING-CREATE-004 LISTING-CREATE-005 LISTING-CREATE-006 LISTING-CREATE-007 LISTING-CREATE-008 LISTING-CREATE-009 LISTING-CREATE-010 LISTING-CREATE-011 LISTING-CREATE-012 LISTING-CREATE-013 LISTING-CREATE-014 LISTING-CREATE-015 LISTING-CREATE-016 MODERATION-001 MODERATION-002 MODERATION-003 MODERATION-004 MODERATION-005 MODERATION-006 MODERATION-007 MODERATION-008 MODERATION-009 MODERATION-010 MODERATION-011 MODERATION-012 MODERATION-013 MODERATION-014 MODERATION-015 MODERATION-016 MODERATION-017 MODERATION-018', 'Dealer A OWNER/MANAGER/STAFF, Dealer B, Admin; fresh plates and valid/invalid data/media.', ['Login as STAFF through normal customer OTP, open account menu → Dealer dashboard → Add vehicle, enter a fresh registration and Continue.', 'Enter some permitted data and Save draft. Refresh and reopen the same draft from Inventory. QA verifies dealer A ownership and STAFF creator on the fixture sheet.', 'Complete all required fields. Try negative/invalid price, year/km and blank required values; submit via the collection to ensure server validation.', 'As STAFF try Submit in UI and POST /v1/dealer/vehicles/{vehicleId}/submit. It must be unavailable/403. As MANAGER or OWNER submit the completed draft; verify PENDING_REVIEW and hidden public URL.', 'As Dealer B read/edit/delete A’s draft ID through the collection; compare with an unknown ID and confirm no changes.', 'As Admin → Listings inspect the review row, data/checklist and six images. Approve only an eligible complete listing. Open /cars and the public URL; confirm ACTIVE and correct dealer.', 'In fresh fixtures choose Request changes and resubmit after correction, then choose Reject and verify finality/non-public history. Record that rejected resubmission differs from changes-requested policy.', 'Use two profiles for duplicate Submit and concurrent approve/reject. Confirm one state/decision and audit entry through QA evidence; no duplicate listing.'], 'All three roles prepare permitted drafts; only OWNER/MANAGER submit; server validates ownership/data; only valid Admin review publishes; rejection/change workflows and audit are consistent.'),
('Enquiry creation, contact, closure and history', 'ENQ-CREATE-001 ENQ-CREATE-002 ENQ-CREATE-003 ENQ-CREATE-004 ENQ-CREATE-005 ENQ-CREATE-006 ENQ-CREATE-007 ENQ-CREATE-008 ENQ-CREATE-009 ENQ-CREATE-010 ENQ-CREATE-011 ENQ-CREATE-012 ENQ-CREATE-013 ENQ-CREATE-014 ENQ-CREATE-015 ENQ-CREATE-016 ENQ-CREATE-017 ENQ-CREATE-018 ENQ-LIFE-001 ENQ-LIFE-002 ENQ-LIFE-003 ENQ-LIFE-004 ENQ-LIFE-005 ENQ-LIFE-006 ENQ-LIFE-007 ENQ-LIFE-008 ENQ-LIFE-009 ENQ-LIFE-010 ENQ-LIFE-011 ENQ-LIFE-012 ENQ-LIFE-013 ENQ-LIFE-014 ENQ-LIFE-015 ENQ-LIFE-016 ENQ-LIFE-017 ENQ-LIFE-018 ENQ-LIFE-019 ENQ-LIFE-020 ENQ-LIFE-021', 'Customer A/B, STAFF/MANAGER/OWNER A, Admin; ACTIVE-A and terminal-state vehicles.', ['Anonymous visitor selects ACTIVE-A → Enquire now; login returns to the intended car. Check name/verified number, cancel and reopen.', 'Send once without Message, and on another car with a Message. Rapidly click/send a duplicate; only the allowed open enquiry should exist.', 'Open customer My enquiries, dealer Enquiries and Admin Enquiries; compare human, phone, message, car, dealer and status.', 'As STAFF open New tab, check the verified contact and choose Mark contacted. Confirm Contacted by that STAFF and time. Try Close in UI and PATCH /v1/dealer/enquiries/{enquiryId} with {"status":"CLOSED"}; expect 403.', 'As MANAGER choose Contacted tab → Close. Verify closed actor/time and customer CLOSED. Repeat permitted actions as OWNER in a new fixture.', 'As Customer B/Dealer B attempt A’s enquiry ID in the collection. Submit unexpected customer/dealer/status fields and an overlong message; expect controlled refusal and unchanged record.', 'Try enquiries on RESERVED, SOLD, WITHDRAWN, DRAFT and REVIEW listings. RESERVED is visible but unavailable for new enquiries; terminal/private listings refuse.', 'QA coordinates sale/suspension between opening the form and Send, concurrent status changes, and member removal after contact. Refresh all three histories; no impossible state, lost records or lost individual actor attribution.'], 'One human-owned lead reaches the correct dealer/Admin, permissions and lifecycle enforced, contact/close actor/time and history persist through related state changes.'),
('Team invitation and permission changes', 'MEMBER-001 MEMBER-002 MEMBER-003 MEMBER-004 MEMBER-005 MEMBER-006 MEMBER-007 MEMBER-008 MEMBER-009 MEMBER-010 MEMBER-011 MEMBER-012 MEMBER-013 MEMBER-014 MEMBER-015 MEMBER-016 MEMBER-029 MEMBER-030 MEMBER-031 MEMBER-032 MEMBER-033 MEMBER-034 MEMBER-035', 'Owner A; existing Customer A; new fictional phone; expired and withdrawn invitation fixtures.', ['Owner → Dealer dashboard → Team → Invite member; enter Customer A phone, choose STAFF, Invite. Cancel/reopen first to verify no unintended invite.', 'Customer A logs in normally and accepts the offered invitation. Select Dealer dashboard in the same account menu; no extra dealer OTP/onboarding or duplicate user.', 'Repeat with MANAGER and a previously unregistered phone. Owner must never be able to invite OWNER through altered role JSON.', 'Invite the same phone twice, accept twice/together in two profiles, try a different person, expired invitation and withdrawn invitation. Expect one membership and controlled refusals.', 'Owner changes MANAGER to STAFF while the member profile stays open; member tries Submit and must be denied. Promote STAFF to MANAGER and retry eligible Submit without logout.', 'As MANAGER/STAFF try Team, invitation, role-change and removal APIs through the collection; expect denial.', 'As the last OWNER attempt self-removal and self-demotion via the collection; expect denial and retained OWNER.'], 'Invitations bind the verified human to the correct dealer once; permissions update immediately; only OWNER manages Team and final OWNER is protected.'),
('Revocation while dealer context is open', 'MEMBER-017 MEMBER-018 MEMBER-019 MEMBER-020 MEMBER-021 MEMBER-022 MEMBER-023 MEMBER-024 MEMBER-025 MEMBER-026 MEMBER-027 MEMBER-028 IDENTITY-010 IDENTITY-011 CROSS-015 CROSS-018 CROSS-020 CROSS-024 CROSS-025 DATA-001 DATA-002 DATA-010', 'STAFF A has a saved competitor car, personal enquiry, created draft and handled dealer enquiry. Owner profile open separately.', ['STAFF logs in through normal customer login and opens Dealer dashboard; keep it open.', 'Owner opens Team → STAFF → Remove and confirms Remove from team.', 'Without logging STAFF out, refresh dashboard, try opening/editing the old draft and mark/contact a lead; protected requests must be denied.', 'STAFF opens account menu → Saved cars and My enquiries, browses /cars and a competitor car; personal account still works.', 'Logout STAFF and login again through normal customer OTP. Personal data remains; former Dealer dashboard remains denied.', 'Owner/MANAGER/Admin reopen STAFF’s created draft and handled enquiry; verify the dealership still owns records and original actor/time/history remains. QA compares pre/post record IDs/counts.'], 'Dealer authorization revoked immediately, personal authentication/data preserved, no cascading dealer deletion or lost historical actor.'),
('Suspension, reinstatement and member separation', 'DEALER-LIFE-001 DEALER-LIFE-002 DEALER-LIFE-003 DEALER-LIFE-004 DEALER-LIFE-005 DEALER-LIFE-006 DEALER-LIFE-007 DEALER-LIFE-008 DEALER-LIFE-009 DEALER-LIFE-010 DEALER-LIFE-011 DEALER-LIFE-012 DEALER-LIFE-013 DEALER-LIFE-014 DEALER-LIFE-015 DEALER-LIFE-016 DEALER-LIFE-017 DEALER-LIFE-018 CROSS-001 CROSS-002 CROSS-003 CROSS-004 CROSS-005 CROSS-006 CROSS-021 CROSS-022 CROSS-023 CROSS-029 ADMIN-DEALER-006 ADMIN-DEALER-007 ADMIN-DEALER-008', 'Dealer A ACTIVE/RESERVED/REVIEW fixtures, enquiries/saved history; one removed member; all profiles kept open.', ['Admin → Dealers → A → Suspend with a reason.', 'In existing OWNER/MANAGER/STAFF sessions attempt inventory mutation and enquiry transition; prohibited operations must be denied immediately.', 'Anonymous visitor checks /cars, dealer portfolio, known car URL and known image URL. Compare suspension visibility policy. Known-image 200 while listing is hidden reproduces BUG-004.', 'Customers and suspended dealer members check personal Saved cars/My enquiries; history must remain non-broken.', 'During suspension remove a member, then Admin Reinstate A. Valid members regain intended operations; the removed member stays denied. Compare listing states, row counts and historical audit records.', 'For permanent deactivation use a fresh disposable fixture only and confirm historical-data policy with QA; do not permanently close a real dealer.'], 'Suspension enforces dealer/public policy without deleting personal/historical data; reinstatement restores only valid states/members and no duplicates.'),
('Listing ACTIVE/RESERVED/SOLD/WITHDRAWN', 'LISTING-LIFE-001 LISTING-LIFE-002 LISTING-LIFE-003 LISTING-LIFE-004 LISTING-LIFE-005 LISTING-LIFE-006 LISTING-LIFE-007 LISTING-LIFE-008 LISTING-LIFE-009 LISTING-LIFE-010 LISTING-LIFE-011 LISTING-LIFE-012 LISTING-LIFE-013 LISTING-LIFE-014 LISTING-LIFE-015 LISTING-LIFE-016 LISTING-LIFE-017 LISTING-LIFE-018 LISTING-LIFE-019 LISTING-LIFE-020 LISTING-LIFE-021 LISTING-LIFE-022 LISTING-LIFE-023 LISTING-LIFE-024 LISTING-LIFE-025 LISTING-LIFE-026 LISTING-LIFE-027 LISTING-LIFE-028 LISTING-LIFE-029 LISTING-LIFE-030 LISTING-LIFE-031 CROSS-008 CROSS-009 CROSS-010 CROSS-011 CROSS-012 CROSS-013 CROSS-014 SEARCH-001 SEARCH-002 SEARCH-003 SEARCH-004 SEARCH-005 SEARCH-006 SEARCH-007 SEARCH-008 SEARCH-009 SEARCH-010 SEARCH-011 SEARCH-012', 'Fresh ACTIVE-A with saved/enquiry history and recorded dealer available count; reset each role/state run.', ['Open /cars, dealer portfolio and public car; compare ACTIVE availability and count.', 'As OWNER/MANAGER reserve through Inventory; compare RESERVED label, public navigation, enquiry refusal and available count. STAFF UI/API must refuse reserve.', 'Request return to ACTIVE through the supported reactivation review, then have Admin approve; no direct relist bypass.', 'On fresh fixtures as OWNER and MANAGER mark SOLD. Confirm public search/portfolio/direct URL and available count exclude it; internal/customer enquiry history persists. STAFF mark-sold API must fail.', 'On fresh ACTIVE fixtures as OWNER and MANAGER Withdraw with reason/note. Verify public disappearance, retained internal/history data and protected reactivation review; STAFF withdraw API must fail.', 'Send forbidden transitions and changed dealer/status fields in the collection; test simultaneous lifecycle moves with QA. Confirm one valid state, audit trail and public/read-model synchronization.'], 'Exact lifecycle, permissions, counts, public visibility and history are consistent; terminal transitions cannot be bypassed.'),
('Unified personal/dealer context and competitor isolation', 'IDENTITY-001 IDENTITY-002 IDENTITY-003 IDENTITY-004 IDENTITY-005 IDENTITY-006 IDENTITY-007 IDENTITY-008 IDENTITY-009 IDENTITY-012 IDENTITY-013 IDENTITY-014 CROSS-026 CROSS-027 CROSS-028 GOLDEN-009', 'OWNER/MANAGER/STAFF A each with ordinary customer OTP login; one nonmember, one dual-dealer member.', ['For each role log in through the public Login/phone path; enter no dealer credentials.', 'Account menu → Dealer dashboard, then personal Saved cars/My enquiries. Switch both ways without another OTP or new identity.', 'From personal context save and enquire about ACTIVE-B. Compare the personal record in Customer/Admin and B’s inbox; employer A must not see that competitor interaction.', 'As an ordinary nonmember open the dealer bookmark/API; denial must not destroy the customer session.', 'For a dual member switch through the offered workspace choices; inventory follows the chosen membership. Alter membership/dealer IDs to another user’s values in the collection; expect denial.', 'QA records session/user counts before/after switching and confirms dealer writes retain dealer plus individual actor.'], 'One verified human can switch authorized workspaces; personal ownership and employer data remain independent; no manipulated tenant choice.'),
('Admin access and enquiry oversight', 'ADMIN-AUTH-001 ADMIN-AUTH-002 ADMIN-AUTH-003 ADMIN-AUTH-004 ADMIN-AUTH-005 ADMIN-AUTH-006 ADMIN-AUTH-007 ADMIN-AUTH-008 ADMIN-AUTH-009 ADMIN-AUTH-010 ADMIN-DEALER-001 ADMIN-DEALER-009 ADMIN-DEALER-010 ADMIN-LISTING-001 ADMIN-LISTING-002 ADMIN-LISTING-003 ADMIN-LISTING-004 ADMIN-LISTING-005 ADMIN-LISTING-006 ADMIN-LISTING-007 ADMIN-LISTING-008 ADMIN-LISTING-009 ADMIN-LISTING-010 ADMIN-ENQ-001 ADMIN-ENQ-002 ADMIN-ENQ-003 ADMIN-ENQ-004 ADMIN-ENQ-005 ADMIN-ENQ-006 ADMIN-ENQ-007 ADMIN-ENQ-008 ADMIN-ENQ-009 ADMIN-ENQ-010 ADMIN-ENQ-011 ADMIN-ENQ-012', 'Admin Google test identity plus non-admin/customer/owner/manager/staff profiles; cross-dealer enquiries.', ['Login to Admin using the supplied authorized Google account. Attempt same entry as non-admin Google and each dealer/customer identity; verify server denial.', 'Admin → Enquiries; search by fictional customer, phone, plate and dealer; filter status/date/dealer and page through all records.', 'Open View for an enquiry. Compare customer name/phone, description, dealer, car, status and history to the fixture sheet and dealer/customer views.', 'Change dealer/listing/member state in separate profiles, then refresh Admin history. Records/actor references must persist.', 'Admin → Dealers/Listings performs permitted review/actions only. Try approving a listing whose dealer becomes suspended during review with QA coordination.', 'Expire/log out Admin and retry its old cookie/API. Confirm bootstrap access cannot create an Admin using a non-allowlisted Google identity.', 'Repeat supported views at mobile/tablet sizes; scroll tables and verify all actions remain usable. BUG-008 is currently reproducible at 390 pixels.'], 'Only authorized Admin identities/scopes operate; aggregation/search/detail/history and responsive actions work without leaking to dealer/customer identities.'),
('Direct API tenant/permission and abuse checks', 'API-SEC-001 API-SEC-002 API-SEC-003 API-SEC-004 API-SEC-005 API-SEC-006 API-SEC-007 API-SEC-008 API-SEC-009 API-SEC-010 API-SEC-011 API-SEC-012 API-SEC-013 API-SEC-014 ABUSE-001 ABUSE-002 ABUSE-003 ABUSE-004 ABUSE-005 ABUSE-006 ABUSE-007 ABUSE-008 ABUSE-009 ABUSE-010 ABUSE-011 ABUSE-012', 'QA-supplied authenticated collection with all role profiles and foreign fixture IDs; rate-limit policy documented.', ['With auth cleared GET dealer vehicles/team/enquiries, customer saved/enquiries and Admin aggregation; each protected collection refuses access.', 'Repeat dealer calls as a nonmember customer; privileged listing transitions as STAFF; Team/profile/KYC writes as MANAGER; Admin calls as OWNER. Verify expected 401/403 and no mutation.', 'As A substitute B vehicle/enquiry/team IDs in GET/PATCH/DELETE requests; compare unknown UUID responses and ask QA to confirm B’s rows unchanged.', 'Send malformed IDs and unexpected dealerId/customerId/role/status/verification fields, unknown filters/cursors, overlong text and invalid enums. Verify controlled errors, no mass assignment, no SQL/stack/token disclosure.', 'Withdraw invitations/remove members/suspend dealer in another profile; repeat stale authenticated and altered-client requests. Confirm no restored privilege.', 'Repeat sensitive requests to documented rate thresholds with QA; verify limits across phone/IP identities. Avoid abuse traffic on production.'], 'Server authorization, tenant ownership, validation, revocation, rate policy and redaction enforce the rules independent of visible UI.'),
('Production, deployment, backup and observability gates', 'PROD-001 PROD-002 PROD-003 PROD-004 PROD-005 PROD-006 PROD-007 PROD-008 PROD-009 PROD-010 PROD-011 PROD-012 PROD-013 DEPLOY-001 DEPLOY-002 DEPLOY-003 DEPLOY-004 DEPLOY-005 DEPLOY-006 DEPLOY-007 DEPLOY-008 DEPLOY-009 DEPLOY-010 OBS-001 OBS-002 OBS-003 OBS-004 OBS-005 OBS-006 OBS-007 OBS-008 OBS-009 OBS-010 OBS-011 OBS-012', 'QA/operations operator, isolated production-like deployment and restore target, configured test providers. No live production writes.', ['Ask the operator to run isolated production startup validation with intended providers, then forbidden MinIO/fake OTP/Mailpit/dev auth/local seed options. Review acceptance/refusal summary without printing credentials. MinIO acceptance reproduces BUG-006.', 'Use the hosted UAT URL to exercise Google callback, OTP delivery, mail sender/links and object uploads/download privacy; compare endpoint/resource identities to the private approved deployment sheet.', 'Operator applies migrations to a copied pre-migration DB, including old-owner/SALES fixtures; compare users/dealers/listings/enquiries/documents and OWNER memberships before/after.', 'Operator performs a deliberately failed migration recovery and a real backup restore into a new isolated DB; you repeat login, roles, history, search and dealer lifecycle on the restored app.', 'Trigger an auth denial, role denial, suspension, permission change, listing/enquiry action and controlled 5xx. Ask operator for redacted correlation/audit/log/health evidence covering each action; no OTP/token/private signed URL should appear.', 'Operator checks production docs/internal/metrics exposure, client bundle secret scan and query index plans. Record missing tooling/resources as not verified, not PASS.'], 'Intended production resources/providers only, forbidden local adapters/seeds rejected, deployment/restore preserves data and authorization, logs trace failures without secrets.'),
('Recovery and races with QA coordination', 'RECOVERY-001 RECOVERY-002 RECOVERY-003 RECOVERY-004 RECOVERY-005 RECOVERY-006 RECOVERY-007 RECOVERY-008 RECOVERY-009 RECOVERY-010 RECOVERY-011 RECOVERY-012 RECOVERY-013 CONCURRENCY-001 CONCURRENCY-002 CONCURRENCY-003 CONCURRENCY-004 CONCURRENCY-005 CONCURRENCY-006 CONCURRENCY-007 CONCURRENCY-008 CONCURRENCY-009 CONCURRENCY-010 CROSS-007 CROSS-016 CROSS-017 CROSS-019', 'Disposable fixtures, two role profiles and operator-controlled failure/lock harness; never block shared or production DB.', ['While you browse/save/enquire, operator disconnects only the isolated API/DB/storage/OTP/Google/mail service one at a time. Expect clear recoverable errors, no false success or partially authorized identity.', 'Restore each service and retry the same action once; compare record IDs/counts and history. Double-click, refresh/back and time out one request before retrying.', 'Two staff edit the same draft; two managers sell/reserve/withdraw; Admin review races edit/submit; dealer suspension races submit/enquiry. Operator releases controlled barriers and supplies final DB/audit state.', 'Two staff/managers change an enquiry simultaneously, two Admins review a dealer, two invitees accept and two legitimate customers enquire. Confirm valid state and retention of legitimate distinct records.', 'For BUG-005, operator holds the listing row lock, starts a MANAGER submit and proves the lock wait. You remove that MANAGER in OWNER Team and observe removal, then operator releases the lock. Expected submit denial/DRAFT; current baseline returns 200/PENDING_REVIEW.', 'Restart only the isolated server, reload persisted drafts/history and confirm identity/session state follows policy.'], 'Safe retry and valid deterministic state; no stale privilege, duplicates, data loss or impossible lifecycle under controlled races/outages.'),
]
covered = set()
for i, (title, ids, setup, steps, expected) in enumerate(journeys, 1):
    mapped = ids.split(); covered.update(mapped)
    statuses = ', '.join(f'{s}: {sum(by_id[id]["status"] == s for id in mapped)}' for s in ['PASS','FAIL','BLOCKED'])
    out += [f'### HUMAN-UAT-J{i:03} — {title}', '', f'Mapped tests: {ids}. Priority: P1. Agent results: {statuses}; consult each registry row.', '', f'Setup: {setup}', '', 'Steps:', '']
    out += [f'{n}. {step}' for n, step in enumerate(steps, 1)]
    out += ['', f'Expected: {expected}', '', 'Human result: **PENDING**. [ ] PASS [ ] FAIL. Notes / screenshot / timestamp / browser: ____________________', '']

routes = {
'PUBLIC': ('Anonymous visitor', '/ and /cars', 'Use homepage search, cars filters, a public car card and dealer directory. Use the fixture-sheet lifecycle variants; use browser refresh/back, and type an invalid route for not-found checks.'),
'AUTH': ('Customer A/new phone', '/login', 'Use Send OTP, Verify and sign in, and the account menu Logout. QA supplies invalid/expired/used proofs and expired session fixtures for the relevant negative case.'),
'CUSTOMER': ('Customer A', '/saved and /enquiries', 'Open both links through the account menu before and after the specified employer/listing change. Keep the same customer profile authenticated.'),
'SAVED': ('Customer A/B', '/cars → save heart → /saved', 'Save/remove the specified fixture car, then apply the exact lifecycle or session change from the test. Compare the same saved row and another customer profile.'),
'ENQ-CREATE': ('Customer A; Dealer A; Admin', '/car/{publicSlug} → Enquire now', 'Open/cancel/reopen the form, inspect verified identity and submit the appropriate message. Use unavailable fixture slugs or altered collection requests for negative cases; compare all three account views.'),
'ENQ-LIFE': ('STAFF/MANAGER/OWNER A; Customer A', '/dealer/enquiries', 'Choose New, Contacted or Closed tab for the fixture, perform the allowed status action, then refresh customer /enquiries and Admin detail. For forbidden moves use the same identity in the API collection.'),
'ONBOARD': ('New dealer applicant; Dealer B', 'Dealer onboarding entry', 'Complete the required identity, business and document steps; leave the specified prerequisite missing or change the document/identity fixture for negative tests. Refresh/resume at the indicated step.'),
'VERIFY': ('Admin; applicant', '/admin/dealers', 'Open the relevant complete/incomplete application and execute the indicated approval/rejection/changes decision. Applicant refreshes its state. Direct approval uses POST /v1/admin/dealers/{dealerId}/approve with {}.'),
'DEALER-LIFE': ('Admin; Dealer A member; Customer A', '/admin/dealers and /dealer', 'Suspend/reinstate the disposable dealer with a reason. In the already-open member/customer/anonymous profiles retry operations, public URLs and personal/history pages; compare fixture IDs/counts.'),
'LISTING-CREATE': ('Specified OWNER/MANAGER/STAFF A; Dealer B', '/dealer/vehicles/new and /dealer/inventory', 'Enter a fresh registration, Continue, enter the specified valid/invalid vehicle fields and Save draft. Reopen the same draft after the indicated navigation or membership change; compare ownership/creator via the QA fixture sheet.'),
'MODERATION': ('OWNER/MANAGER/STAFF A; Admin', '/dealer/inventory and /admin/listings', 'Use the specified incomplete/complete draft. Submit as the stated role; Admin opens the review, checklist/media and approve/reject/request-changes action. Refresh public /cars and the dealer inventory.'),
'MEDIA': ('Admin media operator; visitor', '/admin/listings/{listingId} and /car/{publicSlug}', 'Attach the exact QA StudioCar output to its intended vehicle, test the specified image ordering/count/replacement/error, then inspect the card and gallery arrows/fullscreen. Use the QA collection for foreign private media checks.'),
'LISTING-LIFE': ('OWNER/MANAGER/STAFF A; Customer; Admin', '/dealer/inventory and /cars', 'Reset ACTIVE fixture; choose the indicated Reserve, Mark sold, Withdraw or supported reactivation review. Refresh car/dealer/search/count/customer-history views. Use collection requests for forbidden transitions.'),
'MEMBER': ('OWNER A; invited customer; member', '/dealer/team', 'Invite the fictional phone with the specified role, or change/remove that fixture member. Invitee accepts using the same normal customer identity. Retain the member profile for immediate stale-session checks.'),
'IDENTITY': ('Specified person; nonmember/dual-member fixture', '/login → account menu → Dealer dashboard', 'Login by normal customer OTP, switch to the offered dealer workspace, then return to Saved cars/My enquiries. Try the indicated unauthorized membership choice through the supplied collection.'),
'OWNER': ('OWNER A; Dealer B; Admin', '/dealer', 'Use Inventory, Enquiries, Dealer profile or Team for the specified capability. Confirm all promised actions, then repeat foreign-tenant/Admin API requests from the collection.'),
'MANAGER': ('MANAGER A', '/dealer', 'Use Inventory/Add vehicle/Enquiries for the specified allowed operation. Try Team/profile/KYC/Admin controls and equivalent requests with the same manager identity for forbidden capabilities.'),
'STAFF': ('STAFF A', '/dealer', 'Use Inventory/Add vehicle/Enquiries to prepare draft or mark New contacted. Try Submit/Reserve/Mark sold/Withdraw/Close/Team/profile/KYC/Admin requests for the exact forbidden capability; expect denial and unchanged state.'),
'PROFILE': ('OWNER A; MANAGER/STAFF negative profiles', '/dealer/profile', 'Edit the specified field with valid/invalid fixture values, submit/save and inspect any review/verification requirement. Refresh public dealer profile. Repeat the same write under MANAGER/STAFF identities in the collection.'),
'ADMIN-AUTH': ('Admin/non-admin Google and person profiles', 'Admin sign-in entry', 'Authenticate with the approved Google test account, then repeat as the stated unauthorized identity. For expiry/logout/bootstrap have QA prepare the exact fixture and request the same protected Admin page/API.'),
'ADMIN-DEALER': ('Admin; Dealer A', '/admin/dealers', 'Search/open the disposable application/dealer and execute the exact indicated review/state action. Refresh member/public/customer profiles; request the corresponding audit entry from QA.'),
'ADMIN-LISTING': ('Admin; Dealer A role', '/admin/listings', 'Open the indicated pending/complete/ineligible listing and perform approve/reject/review while a separate member/Admin profile makes the specified state change. Refresh public visibility and request audit evidence.'),
'ADMIN-ENQ': ('Admin; cross-dealer enquiry fixtures', '/admin/enquiries', 'Search by fixture name/phone/plate, choose status/dealer/date filters, Apply and use View on the relevant row. Compare all displayed fields and history to the fixture sheet, including after the indicated related state change.'),
'CROSS': ('Profiles named in this exact scenario', 'Dealer Team/Inventory/Enquiries plus Admin Dealers/Listings', 'Keep the affected profile open, make the named related-entity transition in the second profile, then repeat the original action/read using the unchanged identity and resource ID. QA supplies the pre/post count and actor sheet.'),
'SEARCH': ('Anonymous visitor; dealer/Admin mutation profiles', '/cars and /dealers/{dealerSlug}', 'Record fixture visible IDs and available count; apply the named approval/sale/withdrawal/reservation/suspension/reinstatement, refresh both search and direct portfolio, and compare IDs/counts. Enter altered filter query in the collection for tampering checks.'),
'DATA': ('QA operator plus affected member/customer/Admin', 'The specified lifecycle screen', 'Operator records pre-state IDs/ownership/actor/timestamps/FK checks, you perform the named lifecycle/identity/membership change through UI, operator records post-state checks, and you reopen the corresponding customer/dealer/Admin history.'),
'API-SEC': ('Specified authenticated role or auth cleared', 'QA-supplied Postman collection', 'Send the exact resource operation under the stated identity, substituting a foreign/unknown/malformed ID or unexpected field where requested. Compare HTTP/body with expected denial and confirm the target is unchanged on the QA fixture sheet.'),
'STORAGE': ('QA storage operator; Dealer A/B; anonymous', 'Upload/document/media request collection', 'Request upload credentials for the specified resource/type/size, attempt the altered/foreign commit or private fetch in the indicated profile, and inspect result plus object ownership/cleanup on QA’s sanitized storage sheet.'),
'NOTIFY': ('New dealer applicant; Admin; QA mail operator', 'Onboarding submission and isolated mail inbox', 'Submit the fixture dealer application/state change. Operator records outbox/delivery IDs and received email, temporarily fails email delivery and restores/drains retries. Confirm one business outcome with intended delivery behavior and no assumed unimplemented notification.'),
'RECOVERY': ('Affected user profile; QA failure operator', 'The specified public/dealer/auth/enquiry UI', 'Operator disconnects only the named isolated dependency. Perform the indicated action and record the error; restore dependency, retry once, refresh/back and compare final row/history/auth state using the fixture sheet.'),
'CONCURRENCY': ('Two named role profiles; QA race operator', 'The exact mutation UI/API pair', 'Operator prepares barriers/locks for the specified pair of requests. Execute both operations, release the barrier, record both responses and authoritative final state/audit. For removal-vs-mutation remove only after a lock wait is proved.'),
'BROWSER': ('Specified real browser/device; all relevant profiles', 'Search → car → save/enquire → dealer/Admin critical views', 'Use the actual named browser/OS/device. Complete the critical journeys, show its soft keyboard in forms, exercise dialogs/back/forward/new tabs and inspect overflow/actions. Record unavailable engine/device as not verified.'),
'UX': ('Keyboard/screen-reader operator; relevant customer/dealer/Admin', 'The stated form/dialog/list screen', 'Use Tab/Shift-Tab/Enter/Escape without a pointer, read the field/button name with the screen reader, trigger empty/error/loading/destructive state as specified, and verify focus, labels, next action and confirmation visually and by keyboard.'),
'SEO': ('Anonymous visitor; QA deployment operator', 'Public route plus robots.txt/sitemap.xml', 'Open the specified public fixture/status route, compare title/canonical/description/social/structured data and indexing inclusion to the approved deployed origin sheet; request invalid route or controlled server failure for error experience.'),
'PROD': ('QA deployment/provider operator', 'Isolated production-like deployment settings and hosted UAT URL', 'Operator runs the exact forbidden/required configuration probe without printing secret values, or you exercise the specified live test-provider callback/message/upload. Compare the resource origin and acceptance/refusal to the approved configuration sheet.'),
'DEPLOY': ('QA migration/backup operator', 'Isolated copied pre-migration or restored DB/application', 'Operator executes the specified migration/failure/backup/restore case and supplies before/after row/role/FK evidence. You repeat login, workspace access, listing visibility and enquiry history against the restored app; do not use live production.'),
'OBS': ('QA operations operator; actor performing the workflow', 'The specified workflow and redacted telemetry viewer', 'Trigger the exact operation/failure, note its timestamp/request ID, and ask operator to retrieve correlated request/audit/error/health evidence. Verify actor/state and absence of OTP/token/private URLs without copying credentials.'),
'ABUSE': ('Specified attacker-like test identity; QA rate operator', 'QA-supplied request collection and relevant private bookmark', 'Repeat or manipulate only the named phone/IP/role/dealer/status/invitation/membership/client field in the disposable environment. Verify refusal/rate window and unchanged target state; do not attack a production system.'),
'GOLDEN': ('All named customer/dealer/Admin profiles', 'The exact ordered screens in the scenario', 'Complete the entire arrow-separated journey in the specified order using the same fixture IDs. Use normal login, UI actions and all customer/dealer/Admin views; operator supplies final ownership/actor/audit checks. Do not combine unrelated partial passes.'),
}
out += ['## One verification ticket per canonical test', '', 'Execute P1 tickets before P2. Each ticket inherits the exact fixture IDs and methods from the priority journeys above and the private fixture sheet. A QA operator must prepare unavailable providers, failure states, races or restore fixtures before its human test can be performed. Mark the result only after the entire stated expected condition is observed.', '']
for r in sorted(rows, key=lambda r:(r['priority'],r['ordinal'])):
    actor, route, action = routes[r['group']]
    journey_links = [f'HUMAN-UAT-J{i:03}' for i,j in enumerate(journeys,1) if r['id'] in j[1].split()]
    out += [f"### HUMAN-UAT-{r['ordinal']:03} — {r['id']}", '', f"Priority: {r['priority']}. Agent result: {r['status']}. Bug: {', '.join(r['bugs']) or 'none confirmed'}. Journey: {', '.join(journey_links) or 'use the specific ticket procedure below'}.", '', f'Setup: {actor}; use the private fixture sheet with exactly the lifecycle/identity state in the expected condition below. Obtain any required failure/race/provider fixture from QA before starting.', '', 'Steps:', '', f'1. In the specified isolated profile open {route}. Record the initial visible state and fixture resource IDs.', f'2. {action}', '3. Check the complete expected condition below, including the negative request or related history/ownership where named. Record the actual result and screenshot; ask QA for the matching DB/audit evidence for server-only requirements.', '4. Restore/reset only the disposable fixture before the next test. Do not mark PASS if a prerequisite or required observation is unavailable.', '', f"Expected: {r['scenario']}", '', 'Human result: **PENDING**. [ ] PASS [ ] FAIL. Notes / evidence / timestamp / browser: ____________________', '']

(ROOT / 'HUMAN-UAT.md').write_text('\n'.join(out) + '\n')
(ROOT / 'evidence/human-uat-coverage.json').write_text(json.dumps({'canonical_tickets':len(rows),'priority_p1_tickets':sum(r['priority']=='P1' for r in rows),'priority_p2_tickets':sum(r['priority']=='P2' for r in rows),'all_results':'PENDING','priority_journeys':len(journeys),'ticket_ids':{r['id']:f"HUMAN-UAT-{r['ordinal']:03}" for r in rows}},indent=2)+'\n')
print('Wrote independent human workbook: 556 tickets, 15 priority journeys; all PENDING.')
