import {
  SUPPORT_PRIORITY_LABELS,
  SUPPORT_STATUS_LABELS,
  SupportTicketPriority,
} from '@dealers-drive/contracts';

export const SUPPORT_PRIORITY_OPTIONS = SupportTicketPriority.options.map((value) => ({
  value,
  label: SUPPORT_PRIORITY_LABELS[value],
}));

export const SUPPORT_TICKET_TEXT = {
  back: '← Support Tickets',
  metaTitle: 'Support ticket',
  created: (label: string) => `Created ${label} IST`,
  updated: (label: string) => `Last activity ${label} IST`,
  controls: 'Ticket',
  status: 'Status',
  statusOption: (label: string) => label,
  currentStatus: (label: string) => `${label} (current)`,
  closedFinal: 'Closed tickets are final. The customer is pointed to a new request.',
  priority: 'Priority',
  assignee: 'Assigned to',
  unassigned: 'Unassigned',
  assignToMe: 'Assign to me',
  save: 'Save changes',
  saved: 'Saved.',
  nothingChanged: 'Nothing to save.',
  resolvedOn: (label: string) => `Resolved ${label}`,
  closedOn: (label: string) => `Closed ${label}`,
  customer: 'Customer',
  name: 'Name',
  mobile: 'Mobile',
  verified: 'Verified',
  noNumber: 'No number on file',
  memberSince: 'Customer since',
  ticketCount: (n: number) => `${n.toLocaleString('en-IN')} support request${n === 1 ? '' : 's'}`,
  requests: 'Requests',
  enquiry: 'Related enquiry',
  noEnquiry: 'This request is not linked to an enquiry.',
  enquiryStatus: 'Dealer’s status',
  customerSees: 'Customer sees',
  enquirySent: 'Sent',
  enquiryMessage: 'Enquiry message',
  noEnquiryMessage: 'No message — asked to be contacted.',
  openEnquiry: 'Open enquiry',
  dealer: 'Dealer',
  dealerStatus: 'Dealership status',
  dealerPhone: 'Contact number',
  notEntered: 'Not entered',
  openDealer: 'Open dealer',
  conversation: 'Conversation',
  conversationIntro: 'Visible to the customer.',
  original: 'Original request',
  supportTag: 'Support',
  notes: 'Internal notes',
  notesIntro: 'Only Dealers-Drive admins see these. They are never shown to the customer.',
  noNotes: 'No internal notes yet.',
  history: 'History',
  noHistory: 'No recorded changes.',
  composerLabel: 'Write',
  replyMode: 'Reply to customer',
  noteMode: 'Internal note',
  replyHint: 'The customer will see this reply from “Dealers-Drive support”.',
  noteHint: 'Private. The customer never sees internal notes.',
  replyPlaceholder: 'Write a reply to the customer',
  notePlaceholder: 'e.g. Called the dealer at 14:32 — they say they tried twice.',
  sendReply: 'Send reply to customer',
  addNote: 'Add internal note',
  sending: 'Saving…',
  closedNoReply:
    'This ticket is closed, so it cannot take a reply. You can still add internal notes.',
  timesInIst: 'All times IST.',
} as const;

export const SUPPORT_STATUS_NAME = SUPPORT_STATUS_LABELS;
