/**
 * A hundred and twenty dealerships across four southern states, for local
 * development only.
 *
 * ── Why this is not in `data.ts` ────────────────────────────────────────────
 * `prisma/seed/data.ts` is the **test** fixture: `tests/global-setup.ts` runs
 * `prisma/seed/index.ts` into `dealersdrive_test` before every integration run,
 * and `auth.test.ts` is written against exactly one seeded dealership. A
 * hundred and nineteen more would be a hundred and nineteen more rows in every
 * suite, for no test's benefit, and the file belongs to **F097** besides.
 *
 * This file is the opposite: it exists so a laptop has something to look at.
 * The dealer directory (F085) counts its city chips over every ACTIVE
 * dealership, and one row makes a chip row of one — which tells you nothing
 * about whether the chips work. Nothing in `apps/api/src` imports it, no test
 * runs it, and `pnpm db:seed` does not call it. It runs when a developer asks:
 *
 *     pnpm --filter @dealers-drive/api db:seed:dev
 *
 * ── The geography, and why it is real ───────────────────────────────────────
 * Forty-four towns across twelve districts in four states, because the three
 * location questions the product asks are different questions and only real
 * data shows it:
 *
 *   · the public directory groups by **city** — `slugify(dealer.city)` in
 *     `dealers.repository.ts` — so Katpadi and Vellore are separate chips even
 *     though a buyer would drive between them in twenty minutes;
 *   · the admin console filters by **district**, because support questions are
 *     district-shaped ("every dealer in Ranipet district"), and a district
 *     holds towns whose names give no hint they are related — Arakkonam and
 *     Walajapet share a district with Arcot and nothing else;
 *   · the slug carries the **state**, and until this file held more than one
 *     there was no seeded row that proved it — every portfolio URL ended in
 *     `-tamil-nadu`, so a bug that dropped the segment entirely would have
 *     looked exactly like a bug that dropped it correctly.
 *
 * Seed one town per district and none of the three is visible. Seed these and
 * all three are: four chips resolve to one district, the district filter pulls
 * together towns the city chips keep apart, and four states' worth of slugs
 * differ in their last segment.
 *
 *   Tamil Nadu
 *     Vellore district      Vellore ×4 · Katpadi ×3 · Gudiyatham ×2 · Bagayam ×2
 *     Ranipet district      Ranipet ×3 · Arcot ×3 · Arakkonam ×3 · Walajapet ×2
 *     Tirupattur district   Tirupattur ×3 · Vaniyambadi ×3 · Ambur ×2
 *
 *   Karnataka
 *     Bengaluru Urban       Bengaluru ×4 · Yelahanka ×3 · Kengeri ×2 · Anekal ×2
 *     Mysuru district       Mysuru ×3 · Nanjangud ×3 · Hunsur ×3 · Periyapatna ×2
 *     Belagavi district     Belagavi ×3 · Chikkodi ×3 · Gokak ×2
 *
 *   Andhra Pradesh
 *     Visakhapatnam         Visakhapatnam ×4 · Gajuwaka ×3 · Pendurthi ×2 · Bheemunipatnam ×2
 *     Guntur district       Guntur ×3 · Tenali ×3 · Mangalagiri ×3 · Ponnur ×2
 *     Kurnool district      Kurnool ×3 · Adoni ×3 · Yemmiganur ×2
 *
 *   Kerala
 *     Ernakulam district    Kochi ×4 · Aluva ×3 · Perumbavoor ×2 · Muvattupuzha ×2
 *     Thrissur district     Thrissur ×3 · Chalakudy ×3 · Irinjalakuda ×3 · Kunnamkulam ×2
 *     Kozhikode district    Kozhikode ×3 · Vadakara ×3 · Koyilandy ×2
 *
 * Two of the twelve districts share their name with their largest town, and
 * that is kept rather than tidied away: `dealerSlug` collapses consecutive
 * duplicate segments, so a Vellore-town dealer in Vellore district must come
 * out `…-vellore-tamil-nadu` and not `…-vellore-vellore-tamil-nadu`. Ten
 * districts where the names differ and two where they do not is what makes
 * that branch reachable from seeded data.
 *
 * Pincodes and coordinates are the towns' real ones. `mapsUrl` is built as a
 * Google Maps search link on `www.google.com`, which is one of the hosts
 * `GoogleMapsUrl` in `packages/contracts/src/common.ts` allows — a seed that
 * wrote a link the contract would reject on write is a seed that lies about
 * what the database can hold.
 *
 * GSTINs and PANs are structurally valid and unique but entirely invented:
 * they match the `GSTIN` and `PAN` regexes in `contracts/src/dealer.ts`, where
 * characters 3–12 are the PAN and the leading pair is the state — `33` Tamil
 * Nadu, `29` Karnataka, `37` Andhra Pradesh, `32` Kerala. They belong to
 * nobody. Same for the phone numbers, which sit in four blocks the seeded test
 * dealership does not use so the `users.phone` unique index stays quiet, and
 * one block per state so a stray row can be traced back to where it came from.
 * ────────────────────────────────────────────────────────────────────────────
 */

import { dealerSlug } from '@dealers-drive/contracts';

/**
 * The states, in the order the seed writes and reports them.
 *
 * Exported so `dev-dealers.ts` can print its summary state by state without
 * re-deriving an order from a `Set`, which would give whichever order the rows
 * happen to be in.
 */
export const DEV_STATES = ['Tamil Nadu', 'Karnataka', 'Andhra Pradesh', 'Kerala'] as const;

export type DevState = (typeof DEV_STATES)[number];

/**
 * One town, written once so every row in it cannot disagree about where it is.
 *
 * `state` lives here rather than in a single module constant because the slug
 * is derived from it: a dealership's state has to travel with its town, or a
 * row's address and its URL can be made to disagree by editing one of them.
 */
interface Town {
  city: string;
  district: string;
  state: DevState;
  lat: number;
  lng: number;
}

const TOWNS = {
  // ── Tamil Nadu ────────────────────────────────────────────────────────────
  vellore: {
    city: 'Vellore',
    district: 'Vellore',
    state: 'Tamil Nadu',
    lat: 12.9165,
    lng: 79.1325,
  },
  katpadi: {
    city: 'Katpadi',
    district: 'Vellore',
    state: 'Tamil Nadu',
    lat: 12.9698,
    lng: 79.1378,
  },
  gudiyatham: {
    city: 'Gudiyatham',
    district: 'Vellore',
    state: 'Tamil Nadu',
    lat: 12.945,
    lng: 78.87,
  },
  bagayam: { city: 'Bagayam', district: 'Vellore', state: 'Tamil Nadu', lat: 12.888, lng: 79.118 },
  ranipet: { city: 'Ranipet', district: 'Ranipet', state: 'Tamil Nadu', lat: 12.9276, lng: 79.333 },
  arcot: { city: 'Arcot', district: 'Ranipet', state: 'Tamil Nadu', lat: 12.906, lng: 79.32 },
  arakkonam: {
    city: 'Arakkonam',
    district: 'Ranipet',
    state: 'Tamil Nadu',
    lat: 13.08,
    lng: 79.67,
  },
  walajapet: {
    city: 'Walajapet',
    district: 'Ranipet',
    state: 'Tamil Nadu',
    lat: 12.926,
    lng: 79.363,
  },
  tirupattur: {
    city: 'Tirupattur',
    district: 'Tirupattur',
    state: 'Tamil Nadu',
    lat: 12.496,
    lng: 78.57,
  },
  vaniyambadi: {
    city: 'Vaniyambadi',
    district: 'Tirupattur',
    state: 'Tamil Nadu',
    lat: 12.682,
    lng: 78.62,
  },
  ambur: { city: 'Ambur', district: 'Tirupattur', state: 'Tamil Nadu', lat: 12.791, lng: 78.716 },

  // ── Karnataka ─────────────────────────────────────────────────────────────
  bengaluru: {
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    lat: 12.9716,
    lng: 77.5946,
  },
  yelahanka: {
    city: 'Yelahanka',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    lat: 13.1007,
    lng: 77.5963,
  },
  kengeri: {
    city: 'Kengeri',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    lat: 12.9166,
    lng: 77.4826,
  },
  anekal: {
    city: 'Anekal',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    lat: 12.7106,
    lng: 77.6963,
  },
  mysuru: { city: 'Mysuru', district: 'Mysuru', state: 'Karnataka', lat: 12.2958, lng: 76.6394 },
  nanjangud: {
    city: 'Nanjangud',
    district: 'Mysuru',
    state: 'Karnataka',
    lat: 12.1181,
    lng: 76.6838,
  },
  hunsur: { city: 'Hunsur', district: 'Mysuru', state: 'Karnataka', lat: 12.3036, lng: 76.2928 },
  periyapatna: {
    city: 'Periyapatna',
    district: 'Mysuru',
    state: 'Karnataka',
    lat: 12.3372,
    lng: 76.1,
  },
  belagavi: {
    city: 'Belagavi',
    district: 'Belagavi',
    state: 'Karnataka',
    lat: 15.8497,
    lng: 74.4977,
  },
  chikkodi: { city: 'Chikkodi', district: 'Belagavi', state: 'Karnataka', lat: 16.43, lng: 74.59 },
  gokak: { city: 'Gokak', district: 'Belagavi', state: 'Karnataka', lat: 16.1667, lng: 74.8333 },

  // ── Andhra Pradesh ────────────────────────────────────────────────────────
  visakhapatnam: {
    city: 'Visakhapatnam',
    district: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    lat: 17.6868,
    lng: 83.2185,
  },
  gajuwaka: {
    city: 'Gajuwaka',
    district: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    lat: 17.6833,
    lng: 83.2,
  },
  pendurthi: {
    city: 'Pendurthi',
    district: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    lat: 17.8167,
    lng: 83.1833,
  },
  bheemunipatnam: {
    city: 'Bheemunipatnam',
    district: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    lat: 17.8908,
    lng: 83.4544,
  },
  guntur: {
    city: 'Guntur',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    lat: 16.3067,
    lng: 80.4365,
  },
  tenali: { city: 'Tenali', district: 'Guntur', state: 'Andhra Pradesh', lat: 16.243, lng: 80.64 },
  mangalagiri: {
    city: 'Mangalagiri',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    lat: 16.4307,
    lng: 80.568,
  },
  ponnur: { city: 'Ponnur', district: 'Guntur', state: 'Andhra Pradesh', lat: 16.07, lng: 80.55 },
  kurnool: {
    city: 'Kurnool',
    district: 'Kurnool',
    state: 'Andhra Pradesh',
    lat: 15.8281,
    lng: 78.0373,
  },
  adoni: { city: 'Adoni', district: 'Kurnool', state: 'Andhra Pradesh', lat: 15.63, lng: 77.27 },
  yemmiganur: {
    city: 'Yemmiganur',
    district: 'Kurnool',
    state: 'Andhra Pradesh',
    lat: 15.77,
    lng: 77.48,
  },

  // ── Kerala ────────────────────────────────────────────────────────────────
  kochi: { city: 'Kochi', district: 'Ernakulam', state: 'Kerala', lat: 9.9312, lng: 76.2673 },
  aluva: { city: 'Aluva', district: 'Ernakulam', state: 'Kerala', lat: 10.1081, lng: 76.3517 },
  perumbavoor: {
    city: 'Perumbavoor',
    district: 'Ernakulam',
    state: 'Kerala',
    lat: 10.1074,
    lng: 76.475,
  },
  muvattupuzha: {
    city: 'Muvattupuzha',
    district: 'Ernakulam',
    state: 'Kerala',
    lat: 9.98,
    lng: 76.58,
  },
  thrissur: { city: 'Thrissur', district: 'Thrissur', state: 'Kerala', lat: 10.5276, lng: 76.2144 },
  chalakudy: { city: 'Chalakudy', district: 'Thrissur', state: 'Kerala', lat: 10.307, lng: 76.335 },
  irinjalakuda: {
    city: 'Irinjalakuda',
    district: 'Thrissur',
    state: 'Kerala',
    lat: 10.342,
    lng: 76.21,
  },
  kunnamkulam: {
    city: 'Kunnamkulam',
    district: 'Thrissur',
    state: 'Kerala',
    lat: 10.65,
    lng: 76.07,
  },
  kozhikode: {
    city: 'Kozhikode',
    district: 'Kozhikode',
    state: 'Kerala',
    lat: 11.2588,
    lng: 75.7804,
  },
  vadakara: { city: 'Vadakara', district: 'Kozhikode', state: 'Kerala', lat: 11.6, lng: 75.59 },
  koyilandy: { city: 'Koyilandy', district: 'Kozhikode', state: 'Kerala', lat: 11.44, lng: 75.69 },
} as const satisfies Record<string, Town>;

export interface DevDealer {
  brandName: string;
  legalName: string;
  tagline: string;
  gstin: string;
  pan: string;
  town: keyof typeof TOWNS;
  addressLine: string;
  pincode: string;
  phone: string;
  email: string;
  landline: string;
  ownerName: string;
  establishedYear: number;
  specialities: string[];
  /** `null` renders as "New dealer" — see `responseLabel` in the public service. */
  medianResponseMins: number | null;
}

/**
 * The row as the seed writes it: the town's fields flattened in, and the two
 * derived columns (`mapsUrl`, `workingHours`) built from the same source so a
 * corrected coordinate cannot leave a stale link behind it.
 */
export interface DevDealerRow extends DevDealer, Town {
  /** Derived, not typed: see the note on `DEV_DEALERS` below. */
  slug: string;
  mapsUrl: string;
  workingHours: { mon_sat: string; sun: string | null };
}

/**
 * Sunday is the interesting one. A used-car yard is busiest on a Sunday and
 * most of these open; the ones that close are here so the portfolio page's
 * hours block is exercised in both shapes rather than only the cheerful one.
 */
function hoursFor(index: number): { mon_sat: string; sun: string | null } {
  if (index % 7 === 3) return { mon_sat: '9:30 AM – 8:00 PM', sun: null };
  if (index % 3 === 0) return { mon_sat: '9:00 AM – 8:30 PM', sun: '10:00 AM – 6:00 PM' };
  return { mon_sat: '10:00 AM – 8:00 PM', sun: '10:00 AM – 2:00 PM' };
}

const DEALERS: DevDealer[] = [
  // ══ Tamil Nadu ════════════════════════════════════════════════════════════

  // ── Vellore district ──────────────────────────────────────────────────────
  {
    brandName: 'Annamalai Auto Mart',
    legalName: 'Annamalai Auto Mart Pvt Ltd',
    tagline: 'Fort-road yard since 2009 — every car with a service book.',
    gstin: '33AABCA1001C1ZP',
    pan: 'AABCA1001C',
    town: 'vellore',
    addressLine: '22, Officers Line, Near Fort',
    pincode: '632001',
    phone: '+919842010001',
    email: 'owner@annamalaiautomart.in',
    landline: '0416 222 1001',
    ownerName: 'S. Annamalai',
    establishedYear: 2009,
    specialities: ['Hatchbacks', 'Sedans', 'Single-owner cars'],
    medianResponseMins: 12,
  },
  {
    brandName: 'Green Circle Cars',
    legalName: 'Green Circle Motors LLP',
    tagline: 'Compact SUVs and MUVs, exchange welcome.',
    gstin: '33AACFG1002D1ZQ',
    pan: 'AACFG1002D',
    town: 'vellore',
    addressLine: '7, Bagayam Road, Green Circle',
    pincode: '632009',
    phone: '+919842010002',
    email: 'sales@greencirclecars.in',
    landline: '0416 222 1002',
    ownerName: 'K. Prabhakaran',
    establishedYear: 2016,
    specialities: ['Compact SUVs', 'MUVs', 'Exchange'],
    medianResponseMins: 25,
  },
  {
    brandName: 'Thiru Motors',
    legalName: 'Thiru Motors and Finance',
    tagline: 'Finance sorted before you drive out.',
    gstin: '33AAEFT1003E1ZR',
    pan: 'AAEFT1003E',
    town: 'vellore',
    addressLine: '154, Arcot Road, Sathuvachari',
    pincode: '632009',
    phone: '+919842010003',
    email: 'contact@thirumotors.in',
    landline: '0416 222 1003',
    ownerName: 'M. Thirumurugan',
    establishedYear: 2019,
    specialities: ['Finance assistance', 'Hatchbacks', 'RC transfer'],
    medianResponseMins: null,
  },
  {
    brandName: 'CMC Road Autos',
    legalName: 'CMC Road Autos Enterprises',
    tagline: 'Diesel SUVs, sold and serviced.',
    gstin: '33AAFCC1004F1ZS',
    pan: 'AAFCC1004F',
    town: 'vellore',
    addressLine: '3/91, CMC Hospital Road, Thottapalayam',
    pincode: '632004',
    phone: '+919842010004',
    email: 'desk@cmcroadautos.in',
    landline: '0416 222 1004',
    ownerName: 'A. Ravichandran',
    establishedYear: 2012,
    specialities: ['SUVs', 'Diesel', 'Commercial vehicles'],
    medianResponseMins: 45,
  },
  {
    brandName: 'Katpadi Car Junction',
    legalName: 'Katpadi Car Junction Pvt Ltd',
    tagline: 'Two minutes from the railway junction.',
    gstin: '33AABCK1005G1ZT',
    pan: 'AABCK1005G',
    town: 'katpadi',
    addressLine: '19, Station Road, Katpadi',
    pincode: '632007',
    phone: '+919842010005',
    email: 'owner@katpadicarjunction.in',
    landline: '0416 226 1005',
    ownerName: 'R. Selvakumar',
    establishedYear: 2015,
    specialities: ['Hatchbacks', 'Petrol', 'First-time buyers'],
    medianResponseMins: 8,
  },
  {
    brandName: 'VIT Gate Motors',
    legalName: 'VIT Gate Motors LLP',
    tagline: 'Small cars for people who are new to driving.',
    gstin: '33AACFV1006H1ZU',
    pan: 'AACFV1006H',
    town: 'katpadi',
    addressLine: '61, Chennai–Bengaluru Highway, Near VIT Gate',
    pincode: '632007',
    phone: '+919842010006',
    email: 'hello@vitgatemotors.in',
    landline: '0416 226 1006',
    ownerName: 'D. Hariharan',
    establishedYear: 2020,
    specialities: ['Hatchbacks', 'RC transfer', 'Insurance renewal'],
    medianResponseMins: 15,
  },
  {
    brandName: 'Sri Balaji Cars',
    legalName: 'Sri Balaji Cars and Credits',
    tagline: 'Family cars, family business, since 1998.',
    gstin: '33AAGFS1007J1ZV',
    pan: 'AAGFS1007J',
    town: 'katpadi',
    addressLine: '88, Gandhi Nagar Main Road, Katpadi',
    pincode: '632007',
    phone: '+919842010007',
    email: 'balaji@sribalajicars.in',
    landline: '0416 226 1007',
    ownerName: 'B. Venkatesan',
    establishedYear: 1998,
    specialities: ['Sedans', 'MUVs', 'Single-owner cars'],
    medianResponseMins: 30,
  },
  {
    brandName: 'Gudiyatham Auto Hub',
    legalName: 'Gudiyatham Auto Hub Pvt Ltd',
    tagline: 'The largest yard between Vellore and Krishnagiri.',
    gstin: '33AABCG1008K1ZW',
    pan: 'AABCG1008K',
    town: 'gudiyatham',
    addressLine: '45, Pernambut Road, Gudiyatham',
    pincode: '632602',
    phone: '+919842010008',
    email: 'owner@gudiyathamautohub.in',
    landline: '04171 22 1008',
    ownerName: 'S. Ilangovan',
    establishedYear: 2011,
    specialities: ['SUVs', 'Hatchbacks', 'Home delivery'],
    medianResponseMins: 20,
  },
  {
    brandName: 'Pernambut Road Motors',
    legalName: 'Pernambut Road Motors Enterprises',
    tagline: 'Straight prices, no negotiation theatre.',
    gstin: '33AAFPP1009L1ZX',
    pan: 'AAFPP1009L',
    town: 'gudiyatham',
    addressLine: '12, Bazaar Street, Gudiyatham',
    pincode: '632602',
    phone: '+919842010009',
    email: 'sales@pernambutroadmotors.in',
    landline: '04171 22 1009',
    ownerName: 'P. Murugesan',
    establishedYear: 2018,
    specialities: ['Petrol', 'Sedans', 'Fixed price'],
    medianResponseMins: null,
  },
  {
    brandName: 'Bagayam Motors',
    legalName: 'Bagayam Motors and Spares',
    tagline: 'Cars and the workshop to keep them running.',
    gstin: '33AAGCB1010M1ZY',
    pan: 'AAGCB1010M',
    town: 'bagayam',
    addressLine: '2, Kalinjur Main Road, Bagayam',
    pincode: '632002',
    phone: '+919842010010',
    email: 'workshop@bagayammotors.in',
    landline: '0416 227 1010',
    ownerName: 'N. Karthikeyan',
    establishedYear: 2007,
    specialities: ['Diesel', 'SUVs', 'Free servicing'],
    medianResponseMins: 60,
  },
  {
    brandName: 'Kalinjur Used Cars',
    legalName: 'Kalinjur Used Cars LLP',
    tagline: 'CNG and petrol runabouts, city-driven only.',
    gstin: '33AACFK1011N1ZZ',
    pan: 'AACFK1011N',
    town: 'bagayam',
    addressLine: '31, Bagayam–Kalinjur Road',
    pincode: '632002',
    phone: '+919842010011',
    email: 'contact@kalinjurusedcars.in',
    landline: '0416 227 1011',
    ownerName: 'V. Sathish',
    establishedYear: 2021,
    specialities: ['CNG', 'Petrol', 'Hatchbacks'],
    medianResponseMins: 18,
  },

  // ── Ranipet district ──────────────────────────────────────────────────────
  {
    brandName: 'Ranipet Auto World',
    legalName: 'Ranipet Auto World Pvt Ltd',
    tagline: 'Serving the SIPCOT belt since 2010.',
    gstin: '33AABCR1012P1ZA',
    pan: 'AABCR1012P',
    town: 'ranipet',
    addressLine: '9, SIPCOT Main Road, Ranipet',
    pincode: '632401',
    phone: '+919842010012',
    email: 'owner@ranipetautoworld.in',
    landline: '04172 27 1012',
    ownerName: 'G. Rajendran',
    establishedYear: 2010,
    specialities: ['Sedans', 'Hatchbacks', 'Finance assistance'],
    medianResponseMins: 22,
  },
  {
    brandName: 'Walaja Highway Cars',
    legalName: 'Walaja Highway Cars Enterprises',
    tagline: 'On NH-48, open till nine.',
    gstin: '33AAFCW1013Q1ZB',
    pan: 'AAFCW1013Q',
    town: 'ranipet',
    addressLine: '160, NH-48 Service Road, Ranipet',
    pincode: '632401',
    phone: '+919842010013',
    email: 'sales@walajahighwaycars.in',
    landline: '04172 27 1013',
    ownerName: 'T. Anbarasu',
    establishedYear: 2014,
    specialities: ['Diesel', 'SUVs', 'Extended warranty'],
    medianResponseMins: 35,
  },
  {
    brandName: 'SIPCOT Car Bazaar',
    legalName: 'SIPCOT Car Bazaar LLP',
    tagline: 'Company buy-backs and fleet cars.',
    gstin: '33AAGFS1014R1ZC',
    pan: 'AAGFS1014R',
    town: 'ranipet',
    addressLine: '5, Phase II, SIPCOT Industrial Complex',
    pincode: '632401',
    phone: '+919842010014',
    email: 'fleet@sipcotcarbazaar.in',
    landline: '04172 27 1014',
    ownerName: 'J. Saravanan',
    establishedYear: 2017,
    specialities: ['Fleet cars', 'Sedans', 'Corporate buy-back'],
    medianResponseMins: null,
  },
  {
    brandName: 'Arcot Fort Motors',
    legalName: 'Arcot Fort Motors Pvt Ltd',
    tagline: 'Behind the fort, in front on price.',
    gstin: '33AABCA1015S1ZD',
    pan: 'AABCA1015S',
    town: 'arcot',
    addressLine: '76, Fort Road, Arcot',
    pincode: '632503',
    phone: '+919842010015',
    email: 'owner@arcotfortmotors.in',
    landline: '04172 23 1015',
    ownerName: 'A. Jayaprakash',
    establishedYear: 2004,
    specialities: ['Hatchbacks', 'Sedans', 'Single-owner cars'],
    medianResponseMins: 40,
  },
  {
    brandName: 'Palar Valley Autos',
    legalName: 'Palar Valley Autos Enterprises',
    tagline: 'Pickups and vans for the trade.',
    gstin: '33AAFPP1016T1ZE',
    pan: 'AAFPP1016T',
    town: 'arcot',
    addressLine: '14, Ranipet Road, Arcot',
    pincode: '632503',
    phone: '+919842010016',
    email: 'trade@palarvalleyautos.in',
    landline: '04172 23 1016',
    ownerName: 'S. Elumalai',
    establishedYear: 2013,
    specialities: ['Commercial vehicles', 'Diesel', 'Finance assistance'],
    medianResponseMins: 50,
  },
  {
    brandName: 'Arcot City Cars',
    legalName: 'Arcot City Cars LLP',
    tagline: 'Everything under six lakh.',
    gstin: '33AACFA1017U1ZF',
    pan: 'AACFA1017U',
    town: 'arcot',
    addressLine: '3, Big Bazaar Street, Arcot',
    pincode: '632503',
    phone: '+919842010017',
    email: 'hello@arcotcitycars.in',
    landline: '04172 23 1017',
    ownerName: 'K. Dhanasekaran',
    establishedYear: 2019,
    specialities: ['Hatchbacks', 'Petrol', 'Budget cars'],
    medianResponseMins: 14,
  },
  {
    brandName: 'Arakkonam Junction Motors',
    legalName: 'Arakkonam Junction Motors Pvt Ltd',
    tagline: 'Railway-town stock, railway-town prices.',
    gstin: '33AABCA1018V1ZG',
    pan: 'AABCA1018V',
    town: 'arakkonam',
    addressLine: '27, Station Road, Arakkonam',
    pincode: '631001',
    phone: '+919842010018',
    email: 'owner@arakkonamjunctionmotors.in',
    landline: '04177 22 1018',
    ownerName: 'R. Manoharan',
    establishedYear: 2008,
    specialities: ['Sedans', 'Finance assistance', 'Hatchbacks'],
    medianResponseMins: 28,
  },
  {
    brandName: 'Thakkolam Road Cars',
    legalName: 'Thakkolam Road Cars Enterprises',
    tagline: 'Seven-seaters for large families.',
    gstin: '33AAFCT1019W1ZH',
    pan: 'AAFCT1019W',
    town: 'arakkonam',
    addressLine: '90, Thakkolam Road, Arakkonam',
    pincode: '631001',
    phone: '+919842010019',
    email: 'sales@thakkolamroadcars.in',
    landline: '04177 22 1019',
    ownerName: 'V. Gopinath',
    establishedYear: 2016,
    specialities: ['MUVs', 'SUVs', 'Home test drive'],
    medianResponseMins: null,
  },
  {
    brandName: 'Nemili Auto Traders',
    legalName: 'Nemili Auto Traders LLP',
    tagline: 'Village-route cars, honestly graded.',
    gstin: '33AAGFN1020X1ZJ',
    pan: 'AAGFN1020X',
    town: 'arakkonam',
    addressLine: '8, Nemili Main Road, Arakkonam',
    pincode: '631001',
    phone: '+919842010020',
    email: 'contact@nemiliautotraders.in',
    landline: '04177 22 1020',
    ownerName: 'M. Chandrasekar',
    establishedYear: 2022,
    specialities: ['Budget cars', 'Petrol', 'Graded stock'],
    medianResponseMins: 10,
  },
  {
    brandName: 'Walajapet Motors',
    legalName: 'Walajapet Motors and Finance',
    tagline: 'On the Palar bridge road since 2006.',
    gstin: '33AAGCW1021Y1ZK',
    pan: 'AAGCW1021Y',
    town: 'walajapet',
    addressLine: '55, Bridge Road, Walajapet',
    pincode: '632513',
    phone: '+919842010021',
    email: 'owner@walajapetmotors.in',
    landline: '04172 24 1021',
    ownerName: 'P. Sundaramoorthy',
    establishedYear: 2006,
    specialities: ['Sedans', 'Single-owner cars', 'Insurance renewal'],
    medianResponseMins: 55,
  },
  {
    brandName: 'Palar Bridge Autos',
    legalName: 'Palar Bridge Autos Enterprises',
    tagline: 'Exchange your old car the same day.',
    gstin: '33AAFPP1022Z1ZL',
    pan: 'AAFPP1022Z',
    town: 'walajapet',
    addressLine: '2/17, Arcot Road, Walajapet',
    pincode: '632513',
    phone: '+919842010022',
    email: 'exchange@palarbridgeautos.in',
    landline: '04172 24 1022',
    ownerName: 'S. Baskaran',
    establishedYear: 2015,
    specialities: ['Exchange', 'Hatchbacks', 'Instant valuation'],
    medianResponseMins: 16,
  },

  // ── Tirupattur district ───────────────────────────────────────────────────
  {
    brandName: 'Tirupattur Car Company',
    legalName: 'Tirupattur Car Company Pvt Ltd',
    tagline: 'The district headquarters yard.',
    gstin: '33AABCT1023A1ZM',
    pan: 'AABCT1023A',
    town: 'tirupattur',
    addressLine: '101, Krishnagiri Road, Tirupattur',
    pincode: '635601',
    phone: '+919842010023',
    email: 'owner@tirupatturcarcompany.in',
    landline: '04179 22 1023',
    ownerName: 'C. Rajkumar',
    establishedYear: 2011,
    specialities: ['SUVs', 'Sedans', 'Extended warranty'],
    medianResponseMins: 19,
  },
  {
    brandName: 'Jolarpettai Road Motors',
    legalName: 'Jolarpettai Road Motors LLP',
    tagline: 'Diesel workhorses, checked and certified.',
    gstin: '33AACFJ1024B1ZN',
    pan: 'AACFJ1024B',
    town: 'tirupattur',
    addressLine: '38, Jolarpettai Road, Tirupattur',
    pincode: '635601',
    phone: '+919842010024',
    email: 'sales@jolarpettairoadmotors.in',
    landline: '04179 22 1024',
    ownerName: 'A. Senthilnathan',
    establishedYear: 2018,
    specialities: ['Diesel', 'SUVs', 'Certified engines'],
    medianResponseMins: 33,
  },
  {
    brandName: 'Yelagiri Hills Cars',
    legalName: 'Yelagiri Hills Cars Enterprises',
    tagline: 'Hill-road tested before it is hill-road sold.',
    gstin: '33AAFCY1025C1ZP',
    pan: 'AAFCY1025C',
    town: 'tirupattur',
    addressLine: '6, Athanavur Road, Tirupattur',
    pincode: '635601',
    phone: '+919842010025',
    email: 'contact@yelagirihillscars.in',
    landline: '04179 22 1025',
    ownerName: 'D. Vijayakumar',
    establishedYear: 2020,
    specialities: ['SUVs', 'MUVs', 'Road-tested stock'],
    medianResponseMins: null,
  },
  {
    brandName: 'Vaniyambadi Auto Mart',
    legalName: 'Vaniyambadi Auto Mart Pvt Ltd',
    tagline: 'Leather-town trade, forty years of it.',
    gstin: '33AABCV1026D1ZQ',
    pan: 'AABCV1026D',
    town: 'vaniyambadi',
    addressLine: '44, Bazaar Road, Vaniyambadi',
    pincode: '635751',
    phone: '+919842010026',
    email: 'owner@vaniyambadiautomart.in',
    landline: '04174 22 1026',
    ownerName: 'M. Abdul Rahman',
    establishedYear: 2003,
    specialities: ['Commercial vehicles', 'MUVs', 'Diesel'],
    medianResponseMins: 26,
  },
  {
    brandName: 'NH-44 Car Point',
    legalName: 'NH-44 Car Point LLP',
    tagline: 'Highway yard, open seven days.',
    gstin: '33AACFN1027E1ZR',
    pan: 'AACFN1027E',
    town: 'vaniyambadi',
    addressLine: '2, NH-44 Service Road, Vaniyambadi',
    pincode: '635751',
    phone: '+919842010027',
    email: 'sales@nh44carpoint.in',
    landline: '04174 22 1027',
    ownerName: 'S. Ashok Kumar',
    establishedYear: 2017,
    specialities: ['SUVs', 'Sedans', 'Open Sundays'],
    medianResponseMins: 11,
  },
  {
    brandName: 'Vaniyambadi Family Cars',
    legalName: 'Vaniyambadi Family Cars Enterprises',
    tagline: 'First cars, second chances, fair paperwork.',
    gstin: '33AAFPV1028F1ZS',
    pan: 'AAFPV1028F',
    town: 'vaniyambadi',
    addressLine: '17, Ambur Road, Vaniyambadi',
    pincode: '635751',
    phone: '+919842010028',
    email: 'hello@vaniyambadifamilycars.in',
    landline: '04174 22 1028',
    ownerName: 'K. Fathima Begum',
    establishedYear: 2021,
    specialities: ['Hatchbacks', 'First-time buyers', 'RC transfer'],
    medianResponseMins: 21,
  },
  {
    brandName: 'Ambur Motor House',
    legalName: 'Ambur Motor House Pvt Ltd',
    tagline: 'Since 1996 — the oldest yard in the district.',
    gstin: '33AABCA1029G1ZT',
    pan: 'AABCA1029G',
    town: 'ambur',
    addressLine: '12, Vellore Road, Ambur',
    pincode: '635802',
    phone: '+919842010029',
    email: 'owner@amburmotorhouse.in',
    landline: '04174 24 1029',
    ownerName: 'S. Mohammed Yusuf',
    establishedYear: 1996,
    specialities: ['Sedans', 'Single-owner cars', 'MUVs'],
    medianResponseMins: 48,
  },
  {
    brandName: 'Ambur Star Autos',
    legalName: 'Ambur Star Autos LLP',
    tagline: 'Premium pre-owned, fully reconditioned.',
    gstin: '33AACFA1030H1ZU',
    pan: 'AACFA1030H',
    town: 'ambur',
    addressLine: '3/45, Bypass Road, Ambur',
    pincode: '635802',
    phone: '+919842010030',
    email: 'sales@amburstarautos.in',
    landline: '04174 24 1030',
    ownerName: 'N. Imran Khan',
    establishedYear: 2019,
    specialities: ['Luxury pre-owned', 'SUVs', 'Extended warranty'],
    medianResponseMins: 9,
  },

  // ══ Karnataka ═════════════════════════════════════════════════════════════

  // ── Bengaluru Urban district ──────────────────────────────────────────────
  {
    brandName: 'Cantonment Car Company',
    legalName: 'Cantonment Car Company Pvt Ltd',
    tagline: 'On Infantry Road since 2004 — every car with a full history.',
    gstin: '29AABCC2001K1ZL',
    pan: 'AABCC2001K',
    town: 'bengaluru',
    addressLine: '14, Infantry Road, Shivajinagar',
    pincode: '560001',
    phone: '+919880020001',
    email: 'owner@cantonmentcarcompany.in',
    landline: '080 2286 2001',
    ownerName: 'Ashok Raghavan',
    establishedYear: 2004,
    specialities: ['Sedans', 'Single-owner cars', 'Extended warranty'],
    medianResponseMins: 11,
  },
  {
    brandName: 'Jayanagar Motors',
    legalName: 'Jayanagar Motors LLP',
    tagline: 'Automatics for people who are done with traffic.',
    gstin: '29AACFJ2002L1ZM',
    pan: 'AACFJ2002L',
    town: 'bengaluru',
    addressLine: '452, 11th Main, Jayanagar 4th Block',
    pincode: '560011',
    phone: '+919880020002',
    email: 'sales@jayanagarmotors.in',
    landline: '080 2663 2002',
    ownerName: 'Vinay Shetty',
    establishedYear: 2017,
    specialities: ['Automatics', 'Hatchbacks', 'Exchange'],
    medianResponseMins: 22,
  },
  {
    brandName: 'Silk Board Autos',
    legalName: 'Silk Board Autos and Finance',
    tagline: 'Loan approved before the test drive is over.',
    gstin: '29AAEFS2003M1ZN',
    pan: 'AAEFS2003M',
    town: 'bengaluru',
    addressLine: '9/2, Hosur Main Road, BTM Layout',
    pincode: '560068',
    phone: '+919880020003',
    email: 'contact@silkboardautos.in',
    landline: '080 2668 2003',
    ownerName: 'Manjunath Gowda',
    establishedYear: 2020,
    specialities: ['Finance assistance', 'Compact SUVs', 'RC transfer'],
    medianResponseMins: null,
  },
  {
    brandName: 'Malleswaram Car Bazaar',
    legalName: 'Malleswaram Car Bazaar Pvt Ltd',
    tagline: 'Family cars, sold the way they were bought.',
    gstin: '29AAFCM2004N1ZP',
    pan: 'AAFCM2004N',
    town: 'bengaluru',
    addressLine: '27, 8th Cross, Malleswaram',
    pincode: '560003',
    phone: '+919880020004',
    email: 'desk@malleswaramcarbazaar.in',
    landline: '080 2334 2004',
    ownerName: 'Latha Srinivasan',
    establishedYear: 2011,
    specialities: ['MUVs', 'Hatchbacks', 'Single-owner cars'],
    medianResponseMins: 34,
  },
  {
    brandName: 'Yelahanka Wheels',
    legalName: 'Yelahanka Wheels LLP',
    tagline: 'Airport-road stock, airport-road prices.',
    gstin: '29AAGFY2005P1ZQ',
    pan: 'AAGFY2005P',
    town: 'yelahanka',
    addressLine: '61, Bellary Road, Yelahanka New Town',
    pincode: '560064',
    phone: '+919880020005',
    email: 'hello@yelahankawheels.in',
    landline: '080 2846 2005',
    ownerName: 'Praveen Kumar B',
    establishedYear: 2018,
    specialities: ['Sedans', 'Diesel', 'Highway cars'],
    medianResponseMins: 16,
  },
  {
    brandName: 'Doddaballapur Road Motors',
    legalName: 'Doddaballapur Road Motors Pvt Ltd',
    tagline: 'Pickups, panel vans and the trades.',
    gstin: '29AABCD2006Q1ZR',
    pan: 'AABCD2006Q',
    town: 'yelahanka',
    addressLine: '3/14, Doddaballapur Main Road, Yelahanka',
    pincode: '560064',
    phone: '+919880020006',
    email: 'owner@ddrmotors.in',
    landline: '080 2846 2006',
    ownerName: 'Syed Nazeer Ahmed',
    establishedYear: 2013,
    specialities: ['Commercial vehicles', 'Diesel', 'Fleet buyers'],
    medianResponseMins: 52,
  },
  {
    brandName: 'Air Force Road Autos',
    legalName: 'Air Force Road Autos LLP',
    tagline: 'Service-family cars, priced to move.',
    gstin: '29AACFA2007R1ZS',
    pan: 'AACFA2007R',
    town: 'yelahanka',
    addressLine: '18, Air Force Station Road, Yelahanka',
    pincode: '560063',
    phone: '+919880020007',
    email: 'sales@afroadautos.in',
    landline: '080 2856 2007',
    ownerName: 'Rakesh Menon',
    establishedYear: 2021,
    specialities: ['Single-owner cars', 'Hatchbacks', 'RC transfer'],
    medianResponseMins: 7,
  },
  {
    brandName: 'Kengeri Car Point',
    legalName: 'Kengeri Car Point Enterprises',
    tagline: 'First cars, under five lakh, all of them.',
    gstin: '29AAEFK2008S1ZT',
    pan: 'AAEFK2008S',
    town: 'kengeri',
    addressLine: '76, Mysore Road, Kengeri Satellite Town',
    pincode: '560060',
    phone: '+919880020008',
    email: 'contact@kengericarpoint.in',
    landline: '080 2848 2008',
    ownerName: 'Nagaraj H R',
    establishedYear: 2019,
    specialities: ['Hatchbacks', 'First-time buyers', 'Petrol'],
    medianResponseMins: 19,
  },
  {
    brandName: 'Mysore Road Motors',
    legalName: 'Mysore Road Motors Pvt Ltd',
    tagline: 'CNG and petrol, nothing else on the lot.',
    gstin: '29AAFCM2009T1ZU',
    pan: 'AAFCM2009T',
    town: 'kengeri',
    addressLine: '2/9, Bengaluru–Mysuru Highway, Kengeri',
    pincode: '560060',
    phone: '+919880020009',
    email: 'desk@mysoreroadmotors.in',
    landline: '080 2848 2009',
    ownerName: 'Chandrashekar M',
    establishedYear: 2015,
    specialities: ['CNG', 'Petrol', 'Hatchbacks'],
    medianResponseMins: 28,
  },
  {
    brandName: 'Anekal Auto Yard',
    legalName: 'Anekal Auto Yard LLP',
    tagline: 'Country-road cars for country roads.',
    gstin: '29AAGFA2010U1ZV',
    pan: 'AAGFA2010U',
    town: 'anekal',
    addressLine: '44, Chandapura Road, Anekal',
    pincode: '562106',
    phone: '+919880020010',
    email: 'hello@anekalautoyard.in',
    landline: '080 2782 2010',
    ownerName: 'Shivakumar Reddy',
    establishedYear: 2016,
    specialities: ['Compact SUVs', 'Diesel', 'Exchange'],
    medianResponseMins: 41,
  },
  {
    brandName: 'Attibele Highway Cars',
    legalName: 'Attibele Highway Cars Pvt Ltd',
    tagline: 'On the Hosur road, open seven days.',
    gstin: '29AABCA2011V1ZW',
    pan: 'AABCA2011V',
    town: 'anekal',
    addressLine: '1/88, Hosur Road, Attibele',
    pincode: '562107',
    phone: '+919880020011',
    email: 'owner@attibelehighwaycars.in',
    landline: '080 2782 2011',
    ownerName: 'Faizal Rahman',
    establishedYear: 2012,
    specialities: ['Inter-state transfer', 'Sedans', 'RC transfer'],
    medianResponseMins: 13,
  },

  // ── Mysuru district ───────────────────────────────────────────────────────
  {
    brandName: 'Palace Road Cars',
    legalName: 'Palace Road Cars and Credits',
    tagline: 'Two generations opposite the palace wall.',
    gstin: '29AACFP2012W1ZX',
    pan: 'AACFP2012W',
    town: 'mysuru',
    addressLine: '31, Sayyaji Rao Road, Devaraja Mohalla',
    pincode: '570001',
    phone: '+919880020012',
    email: 'sales@palaceroadcars.in',
    landline: '0821 242 2012',
    ownerName: 'K S Devaraj',
    establishedYear: 1994,
    specialities: ['Sedans', 'Single-owner cars', 'Valuation'],
    medianResponseMins: 26,
  },
  {
    brandName: 'Chamundi Motors',
    legalName: 'Chamundi Motors and Finance',
    tagline: 'Hill-road tested, every one of them.',
    gstin: '29AAEFC2013X1ZY',
    pan: 'AAEFC2013X',
    town: 'mysuru',
    addressLine: '108, JLB Road, Lakshmipuram',
    pincode: '570004',
    phone: '+919880020013',
    email: 'contact@chamundimotors.in',
    landline: '0821 242 2013',
    ownerName: 'Harish Bhat',
    establishedYear: 2010,
    specialities: ['Pre-delivery inspection', 'Hatchbacks', 'Finance assistance'],
    medianResponseMins: 18,
  },
  {
    brandName: 'Saraswathipuram Autos',
    legalName: 'Saraswathipuram Autos Pvt Ltd',
    tagline: 'Small cars for a small city.',
    gstin: '29AAFCS2014Y1ZA',
    pan: 'AAFCS2014Y',
    town: 'mysuru',
    addressLine: '5/2, 100 Feet Road, Saraswathipuram',
    pincode: '570009',
    phone: '+919880020014',
    email: 'desk@saraswathipuramautos.in',
    landline: '0821 251 2014',
    ownerName: 'Anitha Rao',
    establishedYear: 2018,
    specialities: ['Hatchbacks', 'Petrol', 'First-time buyers'],
    medianResponseMins: 9,
  },
  {
    brandName: 'Nanjangud Car Mandi',
    legalName: 'Nanjangud Car Mandi LLP',
    tagline: 'The Sunday yard on the Ooty road.',
    gstin: '29AAGFN2015Z1ZB',
    pan: 'AAGFN2015Z',
    town: 'nanjangud',
    addressLine: '12, Ooty Road, Nanjangud',
    pincode: '571301',
    phone: '+919880020015',
    email: 'hello@nanjangudcarmandi.in',
    landline: '08221 22 2015',
    ownerName: 'Mahadeva Swamy',
    establishedYear: 2014,
    specialities: ['Budget cars', 'Hatchbacks', 'Exchange'],
    medianResponseMins: 47,
  },
  {
    brandName: 'Kabini Motors',
    legalName: 'Kabini Motors Pvt Ltd',
    tagline: 'Four-wheel drive, properly checked.',
    gstin: '29AABCK2016A1ZC',
    pan: 'AABCK2016A',
    town: 'nanjangud',
    addressLine: '9, Mysuru Road, Nanjangud',
    pincode: '571301',
    phone: '+919880020016',
    email: 'owner@kabinimotors.in',
    landline: '08221 22 2016',
    ownerName: 'Girish Nayak',
    establishedYear: 2009,
    specialities: ['SUVs', 'Four-wheel drive', 'Diesel'],
    medianResponseMins: 33,
  },
  {
    brandName: 'Temple Town Autos',
    legalName: 'Temple Town Autos Enterprises',
    tagline: 'Paperwork done before you ask about it.',
    gstin: '29AACFT2017B1ZD',
    pan: 'AACFT2017B',
    town: 'nanjangud',
    addressLine: '2/45, Chamarajanagar Road, Nanjangud',
    pincode: '571302',
    phone: '+919880020017',
    email: 'contact@templetownautos.in',
    landline: '08221 23 2017',
    ownerName: 'Basavaraju N',
    establishedYear: 2022,
    specialities: ['RC transfer', 'Insurance renewal', 'Hatchbacks'],
    medianResponseMins: null,
  },
  {
    brandName: 'Hunsur Auto Centre',
    legalName: 'Hunsur Auto Centre and Workshop',
    tagline: 'We sell it, we service it, on the same plot.',
    gstin: '29AAEFH2018C1ZE',
    pan: 'AAEFH2018C',
    town: 'hunsur',
    addressLine: '17, Mysuru–Madikeri Highway, Hunsur',
    pincode: '571105',
    phone: '+919880020018',
    email: 'desk@hunsurautocentre.in',
    landline: '08222 25 2018',
    ownerName: 'Ramesh Kumar D',
    establishedYear: 2008,
    specialities: ['Workshop on site', 'Diesel', 'MUVs'],
    medianResponseMins: 38,
  },
  {
    brandName: 'Coorg Road Cars',
    legalName: 'Coorg Road Cars LLP',
    tagline: 'Estate cars off the Kodagu plantations.',
    gstin: '29AAFCC2019D1ZF',
    pan: 'AAFCC2019D',
    town: 'hunsur',
    addressLine: '3, Madikeri Road, Hunsur',
    pincode: '571105',
    phone: '+919880020019',
    email: 'sales@coorgroadcars.in',
    landline: '08222 25 2019',
    ownerName: 'Ponnappa M A',
    establishedYear: 2013,
    specialities: ['SUVs', 'Four-wheel drive', 'Single-owner cars'],
    medianResponseMins: 24,
  },
  {
    brandName: 'Hunsur Wheels and Finance',
    legalName: 'Hunsur Wheels and Finance LLP',
    tagline: 'Small-town lending, same-day decisions.',
    gstin: '29AAGFH2020E1ZG',
    pan: 'AAGFH2020E',
    town: 'hunsur',
    addressLine: '58, Bus Stand Road, Hunsur',
    pincode: '571105',
    phone: '+919880020020',
    email: 'hello@hunsurwheels.in',
    landline: '08222 26 2020',
    ownerName: 'Suresh Gowda K',
    establishedYear: 2020,
    specialities: ['Finance assistance', 'Budget cars', 'Exchange'],
    medianResponseMins: 15,
  },
  {
    brandName: 'Periyapatna Motors',
    legalName: 'Periyapatna Motors Pvt Ltd',
    tagline: 'Tobacco-belt cars, straight prices.',
    gstin: '29AABCP2021F1ZH',
    pan: 'AABCP2021F',
    town: 'periyapatna',
    addressLine: '21, Main Road, Periyapatna',
    pincode: '571107',
    phone: '+919880020021',
    email: 'owner@periyapatnamotors.in',
    landline: '08223 27 2021',
    ownerName: 'Lokesh B S',
    establishedYear: 2011,
    specialities: ['Fixed price', 'Hatchbacks', 'Sedans'],
    medianResponseMins: 44,
  },
  {
    brandName: 'Bettadapura Road Autos',
    legalName: 'Bettadapura Road Autos Enterprises',
    tagline: 'Pickups and load carriers, nothing fancy.',
    gstin: '29AACFB2022G1ZJ',
    pan: 'AACFB2022G',
    town: 'periyapatna',
    addressLine: '6/1, Bettadapura Road, Periyapatna',
    pincode: '571107',
    phone: '+919880020022',
    email: 'contact@bettadapuraroadautos.in',
    landline: '08223 27 2022',
    ownerName: 'Nanjunda Shetty',
    establishedYear: 2017,
    specialities: ['Commercial vehicles', 'Diesel', 'Budget cars'],
    medianResponseMins: 56,
  },

  // ── Belagavi district ─────────────────────────────────────────────────────
  {
    brandName: 'Camp Road Car Company',
    legalName: 'Camp Road Car Company Pvt Ltd',
    tagline: 'Border-town stock, both sides of it.',
    gstin: '29AAEFC2023H1ZK',
    pan: 'AAEFC2023H',
    town: 'belagavi',
    addressLine: '48, Khanapur Road, Camp',
    pincode: '590001',
    phone: '+919880020023',
    email: 'sales@camproadcars.in',
    landline: '0831 242 2023',
    ownerName: 'Sanjay Patil',
    establishedYear: 2007,
    specialities: ['Inter-state transfer', 'Sedans', 'Single-owner cars'],
    medianResponseMins: 21,
  },
  {
    brandName: 'Tilakwadi Motors',
    legalName: 'Tilakwadi Motors LLP',
    tagline: 'Diesel SUVs for the ghat roads.',
    gstin: '29AAFCT2024J1ZL',
    pan: 'AAFCT2024J',
    town: 'belagavi',
    addressLine: '2/17, First Railway Gate Road, Tilakwadi',
    pincode: '590006',
    phone: '+919880020024',
    email: 'desk@tilakwadimotors.in',
    landline: '0831 247 2024',
    ownerName: 'Mahesh Kulkarni',
    establishedYear: 2015,
    specialities: ['SUVs', 'Diesel', 'Highway cars'],
    medianResponseMins: 30,
  },
  {
    brandName: 'Khanapur Road Autos',
    legalName: 'Khanapur Road Autos Enterprises',
    tagline: 'Under four lakh, over a hundred cars.',
    gstin: '29AAGFK2025K1ZM',
    pan: 'AAGFK2025K',
    town: 'belagavi',
    addressLine: '90, Khanapur Road, Vadagaon',
    pincode: '590005',
    phone: '+919880020025',
    email: 'hello@khanapurroadautos.in',
    landline: '0831 247 2025',
    ownerName: 'Imtiaz Sheikh',
    establishedYear: 2019,
    specialities: ['Budget cars', 'Hatchbacks', 'Exchange'],
    medianResponseMins: null,
  },
  {
    brandName: 'Chikkodi Car Junction',
    legalName: 'Chikkodi Car Junction Pvt Ltd',
    tagline: 'Sugar-belt cars, cash or finance.',
    gstin: '29AABCC2026L1ZN',
    pan: 'AABCC2026L',
    town: 'chikkodi',
    addressLine: '11, Sangli Road, Chikkodi',
    pincode: '591201',
    phone: '+919880020026',
    email: 'owner@chikkodicarjunction.in',
    landline: '08338 27 2026',
    ownerName: 'Shrikant Desai',
    establishedYear: 2012,
    specialities: ['Sedans', 'MUVs', 'Finance assistance'],
    medianResponseMins: 36,
  },
  {
    brandName: 'Krishna Valley Motors',
    legalName: 'Krishna Valley Motors LLP',
    tagline: 'Seven-seaters for large families.',
    gstin: '29AACFK2027M1ZP',
    pan: 'AACFK2027M',
    town: 'chikkodi',
    addressLine: '4/22, Nipani Road, Chikkodi',
    pincode: '591201',
    phone: '+919880020027',
    email: 'sales@krishnavalleymotors.in',
    landline: '08338 27 2027',
    ownerName: 'Vidya Jadhav',
    establishedYear: 2016,
    specialities: ['MUVs', 'Seven-seaters', 'Diesel'],
    medianResponseMins: 14,
  },
  {
    brandName: 'Nipani Road Autos',
    legalName: 'Nipani Road Autos Enterprises',
    tagline: 'Open at six, because the trucks are.',
    gstin: '29AAEFN2028N1ZQ',
    pan: 'AAEFN2028N',
    town: 'chikkodi',
    addressLine: '1/5, NH-48 Service Road, Chikkodi',
    pincode: '591201',
    phone: '+919880020028',
    email: 'contact@nipaniroadautos.in',
    landline: '08338 28 2028',
    ownerName: 'Rajendra Kamble',
    establishedYear: 2021,
    specialities: ['Commercial vehicles', 'Diesel', 'Highway cars'],
    medianResponseMins: 49,
  },
  {
    brandName: 'Gokak Falls Motors',
    legalName: 'Gokak Falls Motors Pvt Ltd',
    tagline: 'The oldest yard between Belagavi and Bagalkot.',
    gstin: '29AAFCG2029P1ZR',
    pan: 'AAFCG2029P',
    town: 'gokak',
    addressLine: '7, Market Road, Gokak',
    pincode: '591307',
    phone: '+919880020029',
    email: 'owner@gokakfallsmotors.in',
    landline: '08332 22 2029',
    ownerName: 'Basavaraj Hiremath',
    establishedYear: 1999,
    specialities: ['Sedans', 'Valuation', 'Single-owner cars'],
    medianResponseMins: 27,
  },
  {
    brandName: 'Ghataprabha Auto Mart',
    legalName: 'Ghataprabha Auto Mart LLP',
    tagline: 'Reconditioned properly, or not sold.',
    gstin: '29AAGFG2030Q1ZS',
    pan: 'AAGFG2030Q',
    town: 'gokak',
    addressLine: '38, Ghataprabha Road, Gokak',
    pincode: '591307',
    phone: '+919880020030',
    email: 'sales@ghataprabhaautomart.in',
    landline: '08332 22 2030',
    ownerName: 'Prakash Angadi',
    establishedYear: 2018,
    specialities: ['Reconditioned', 'Extended warranty', 'Hatchbacks'],
    medianResponseMins: 10,
  },

  // ══ Andhra Pradesh ════════════════════════════════════════════════════════

  // ── Visakhapatnam district ────────────────────────────────────────────────
  {
    brandName: 'Beach Road Autos',
    legalName: 'Beach Road Autos Pvt Ltd',
    tagline: 'Coastal cars, checked underneath for rust.',
    gstin: '37AABCB3001T1ZU',
    pan: 'AABCB3001T',
    town: 'visakhapatnam',
    addressLine: '24, Beach Road, Lawsons Bay Colony',
    pincode: '530017',
    phone: '+919848030001',
    email: 'owner@beachroadautos.in',
    landline: '0891 275 3001',
    ownerName: 'P. Srinivasa Rao',
    establishedYear: 2010,
    specialities: ['Pre-delivery inspection', 'Sedans', 'Single-owner cars'],
    medianResponseMins: 17,
  },
  {
    brandName: 'Dwaraka Nagar Motors',
    legalName: 'Dwaraka Nagar Motors LLP',
    tagline: 'City hatchbacks, twelve years on the same street.',
    gstin: '37AACFD3002U1ZV',
    pan: 'AACFD3002U',
    town: 'visakhapatnam',
    addressLine: '50-11-9, Nowroji Road, Dwaraka Nagar',
    pincode: '530016',
    phone: '+919848030002',
    email: 'sales@dwarakanagarmotors.in',
    landline: '0891 256 3002',
    ownerName: 'K. Lakshmi Prasanna',
    establishedYear: 2013,
    specialities: ['Hatchbacks', 'Petrol', 'Fixed price'],
    medianResponseMins: 23,
  },
  {
    brandName: 'Steel City Car Bazaar',
    legalName: 'Steel City Car Bazaar and Finance',
    tagline: 'Salary-slip finance for plant employees.',
    gstin: '37AAEFS3003V1ZW',
    pan: 'AAEFS3003V',
    town: 'visakhapatnam',
    addressLine: '9-14-2, NAD Kotha Road, Malkapuram',
    pincode: '530011',
    phone: '+919848030003',
    email: 'contact@steelcitycarbazaar.in',
    landline: '0891 257 3003',
    ownerName: 'M. Appala Naidu',
    establishedYear: 2016,
    specialities: ['Finance assistance', 'Sedans', 'Exchange'],
    medianResponseMins: 39,
  },
  {
    brandName: 'MVP Colony Cars',
    legalName: 'MVP Colony Cars Pvt Ltd',
    tagline: 'Automatics and premium pre-owned.',
    gstin: '37AAFCM3004W1ZX',
    pan: 'AAFCM3004W',
    town: 'visakhapatnam',
    addressLine: '10-50-18, Sector 4, MVP Colony',
    pincode: '530017',
    phone: '+919848030004',
    email: 'desk@mvpcolonycars.in',
    landline: '0891 254 3004',
    ownerName: 'V. Ramesh Babu',
    establishedYear: 2018,
    specialities: ['Luxury pre-owned', 'Automatics', 'Extended warranty'],
    medianResponseMins: 8,
  },
  {
    brandName: 'Gajuwaka Auto Point',
    legalName: 'Gajuwaka Auto Point LLP',
    tagline: 'Shift-worker hours — open till ten.',
    gstin: '37AAGFG3005X1ZY',
    pan: 'AAGFG3005X',
    town: 'gajuwaka',
    addressLine: '2-88, Old Gajuwaka Main Road',
    pincode: '530026',
    phone: '+919848030005',
    email: 'hello@gajuwakaautopoint.in',
    landline: '0891 258 3005',
    ownerName: 'B. Trinadha Rao',
    establishedYear: 2017,
    specialities: ['Budget cars', 'Hatchbacks', 'Late hours'],
    medianResponseMins: 12,
  },
  {
    brandName: 'Kurmannapalem Motors',
    legalName: 'Kurmannapalem Motors Enterprises',
    tagline: 'Load carriers and crew cabs for the contractors.',
    gstin: '37AABCK3006Y1ZA',
    pan: 'AABCK3006Y',
    town: 'gajuwaka',
    addressLine: '6-30, Kurmannapalem Junction',
    pincode: '530046',
    phone: '+919848030006',
    email: 'owner@kurmannapalemmotors.in',
    landline: '0891 258 3006',
    ownerName: 'Sk. Jaffar Basha',
    establishedYear: 2014,
    specialities: ['Commercial vehicles', 'Fleet buyers', 'Diesel'],
    medianResponseMins: 54,
  },
  {
    brandName: 'Anakapalle Road Autos',
    legalName: 'Anakapalle Road Autos LLP',
    tagline: 'Exchange your old one, drive out today.',
    gstin: '37AACFA3007Z1ZB',
    pan: 'AACFA3007Z',
    town: 'gajuwaka',
    addressLine: '11-4-7, Anakapalle Road, Gajuwaka',
    pincode: '530026',
    phone: '+919848030007',
    email: 'sales@anakapalleroadautos.in',
    landline: '0891 259 3007',
    ownerName: 'G. Satyanarayana',
    establishedYear: 2020,
    specialities: ['Exchange', 'Valuation', 'Hatchbacks'],
    medianResponseMins: 20,
  },
  {
    brandName: 'Pendurthi Car Company',
    legalName: 'Pendurthi Car Company Pvt Ltd',
    tagline: 'Highway yard on the Srikakulam road.',
    gstin: '37AAEFP3008A1ZC',
    pan: 'AAEFP3008A',
    town: 'pendurthi',
    addressLine: '1-92, NH-16, Pendurthi',
    pincode: '531173',
    phone: '+919848030008',
    email: 'contact@pendurthicarcompany.in',
    landline: '0891 274 3008',
    ownerName: 'D. Venkata Ramana',
    establishedYear: 2011,
    specialities: ['Large stock', 'Sedans', 'Home test drive'],
    medianResponseMins: 31,
  },
  {
    brandName: 'Sabbavaram Junction Cars',
    legalName: 'Sabbavaram Junction Cars Enterprises',
    tagline: 'Small yard, no salesmen, honest tags.',
    gstin: '37AAFCS3009B1ZD',
    pan: 'AAFCS3009B',
    town: 'pendurthi',
    addressLine: '3-40, Sabbavaram Road, Pendurthi',
    pincode: '531173',
    phone: '+919848030009',
    email: 'desk@sabbavaramjunctioncars.in',
    landline: '0891 274 3009',
    ownerName: 'T. Nagamani',
    establishedYear: 2022,
    specialities: ['Budget cars', 'Hatchbacks', 'RC transfer'],
    medianResponseMins: null,
  },
  {
    brandName: 'Bheemili Beach Motors',
    legalName: 'Bheemili Beach Motors LLP',
    tagline: 'Weekend-drive cars, coastal-checked.',
    gstin: '37AAGFB3010C1ZE',
    pan: 'AAGFB3010C',
    town: 'bheemunipatnam',
    addressLine: '8, Beach Road, Bheemunipatnam',
    pincode: '531163',
    phone: '+919848030010',
    email: 'hello@bheemilibeachmotors.in',
    landline: '08933 22 3010',
    ownerName: 'A. Kiran Kumar',
    establishedYear: 2019,
    specialities: ['Compact SUVs', 'Petrol', 'Single-owner cars'],
    medianResponseMins: 25,
  },
  {
    brandName: 'Bhimili Auto Traders',
    legalName: 'Bhimili Auto Traders Pvt Ltd',
    tagline: 'Since 2002 — the yard the fishermen use.',
    gstin: '37AABCB3011D1ZF',
    pan: 'AABCB3011D',
    town: 'bheemunipatnam',
    addressLine: '2/61, Harbour Road, Bheemunipatnam',
    pincode: '531163',
    phone: '+919848030011',
    email: 'owner@bhimiliautotraders.in',
    landline: '08933 22 3011',
    ownerName: 'Ch. Simhachalam',
    establishedYear: 2002,
    specialities: ['Commercial vehicles', 'Budget cars', 'Valuation'],
    medianResponseMins: 46,
  },

  // ── Guntur district ───────────────────────────────────────────────────────
  {
    brandName: 'Brodipet Car House',
    legalName: 'Brodipet Car House Pvt Ltd',
    tagline: 'In the lanes since 2006, priced for the town.',
    gstin: '37AACFB3012E1ZG',
    pan: 'AACFB3012E',
    town: 'guntur',
    addressLine: '5-37-84, 4/2 Brodipet',
    pincode: '522002',
    phone: '+919848030012',
    email: 'sales@brodipetcarhouse.in',
    landline: '0863 223 3012',
    ownerName: 'N. Koteswara Rao',
    establishedYear: 2006,
    specialities: ['Sedans', 'Diesel', 'Fixed price'],
    medianResponseMins: 29,
  },
  {
    brandName: 'Chilli Yard Motors',
    legalName: 'Chilli Yard Motors and Finance',
    tagline: 'Harvest-season finance, farmer terms.',
    gstin: '37AAEFC3013F1ZH',
    pan: 'AAEFC3013F',
    town: 'guntur',
    addressLine: '12-9-40, Mirchi Yard Road, Guntur',
    pincode: '522004',
    phone: '+919848030013',
    email: 'contact@chilliyardmotors.in',
    landline: '0863 224 3013',
    ownerName: 'P. Nagendra Babu',
    establishedYear: 2015,
    specialities: ['Finance assistance', 'MUVs', 'Commercial vehicles'],
    medianResponseMins: 42,
  },
  {
    brandName: 'Lakshmipuram Autos',
    legalName: 'Lakshmipuram Autos LLP',
    tagline: 'Automatics, because the traffic won.',
    gstin: '37AAFCL3014G1ZJ',
    pan: 'AAFCL3014G',
    town: 'guntur',
    addressLine: '6-14-22, Lakshmipuram Main Road',
    pincode: '522007',
    phone: '+919848030014',
    email: 'desk@lakshmipuramautos.in',
    landline: '0863 225 3014',
    ownerName: 'S. Padmavathi',
    establishedYear: 2021,
    specialities: ['Automatics', 'Petrol', 'Hatchbacks'],
    medianResponseMins: 11,
  },
  {
    brandName: 'Tenali Car Mandi',
    legalName: 'Tenali Car Mandi Enterprises',
    tagline: 'Delta-district stock, forty cars on the lot.',
    gstin: '37AAGFT3015H1ZK',
    pan: 'AAGFT3015H',
    town: 'tenali',
    addressLine: '9-2-14, Kothapeta, Tenali',
    pincode: '522201',
    phone: '+919848030015',
    email: 'hello@tenalicarmandi.in',
    landline: '08644 22 3015',
    ownerName: 'K. Venkateswarlu',
    establishedYear: 2009,
    specialities: ['Large stock', 'Sedans', 'Exchange'],
    medianResponseMins: 35,
  },
  {
    brandName: 'Kollipara Road Cars',
    legalName: 'Kollipara Road Cars Pvt Ltd',
    tagline: 'Paddy-country pickups and jeeps.',
    gstin: '37AABCK3016J1ZL',
    pan: 'AABCK3016J',
    town: 'tenali',
    addressLine: '4-88, Kollipara Road, Tenali',
    pincode: '522201',
    phone: '+919848030016',
    email: 'owner@kolliperaroadcars.in',
    landline: '08644 22 3016',
    ownerName: 'B. Rambabu',
    establishedYear: 2013,
    specialities: ['Four-wheel drive', 'Diesel', 'Commercial vehicles'],
    medianResponseMins: 50,
  },
  {
    brandName: 'Tenali Auto Exchange',
    legalName: 'Tenali Auto Exchange LLP',
    tagline: 'We buy first and sell second.',
    gstin: '37AACFT3017K1ZM',
    pan: 'AACFT3017K',
    town: 'tenali',
    addressLine: '2-1-9, Ramalingeswara Pet, Tenali',
    pincode: '522202',
    phone: '+919848030017',
    email: 'sales@tenaliautoexchange.in',
    landline: '08644 23 3017',
    ownerName: 'M. Sivaji Rao',
    establishedYear: 2018,
    specialities: ['Exchange', 'Valuation', 'Reconditioned'],
    medianResponseMins: 16,
  },
  {
    brandName: 'Capital Region Motors',
    legalName: 'Capital Region Motors Pvt Ltd',
    tagline: 'Amaravati-road stock, government-employee finance.',
    gstin: '37AAEFC3018L1ZN',
    pan: 'AAEFC3018L',
    town: 'mangalagiri',
    addressLine: '7-40, Amaravati Road, Mangalagiri',
    pincode: '522503',
    phone: '+919848030018',
    email: 'contact@capitalregionmotors.in',
    landline: '0863 229 3018',
    ownerName: 'Y. Sudhakar Reddy',
    establishedYear: 2019,
    specialities: ['Finance assistance', 'Sedans', 'Automatics'],
    medianResponseMins: 13,
  },
  {
    brandName: 'Mangalagiri Wheels',
    legalName: 'Mangalagiri Wheels Enterprises',
    tagline: 'Under six lakh, checked by an ex-workshop man.',
    gstin: '37AAFCM3019M1ZP',
    pan: 'AAFCM3019M',
    town: 'mangalagiri',
    addressLine: '3-12-6, Chinakakani, Mangalagiri',
    pincode: '522503',
    phone: '+919848030019',
    email: 'desk@mangalagiriwheels.in',
    landline: '0863 229 3019',
    ownerName: 'R. Subba Rao',
    establishedYear: 2017,
    specialities: ['Pre-delivery inspection', 'Hatchbacks', 'Budget cars'],
    medianResponseMins: 26,
  },
  {
    brandName: 'Undavalli Auto Traders',
    legalName: 'Undavalli Auto Traders LLP',
    tagline: 'Riverside yard, seven days a week.',
    gstin: '37AAGFU3020N1ZQ',
    pan: 'AAGFU3020N',
    town: 'mangalagiri',
    addressLine: '1-5-30, Undavalli Centre, Mangalagiri',
    pincode: '522501',
    phone: '+919848030020',
    email: 'hello@undavalliautotraders.in',
    landline: '0863 230 3020',
    ownerName: 'J. Anil Kumar',
    establishedYear: 2020,
    specialities: ['Compact SUVs', 'Exchange', 'RC transfer'],
    medianResponseMins: 22,
  },
  {
    brandName: 'Ponnur Motor Works',
    legalName: 'Ponnur Motor Works and Workshop',
    tagline: 'Sold and serviced under the same roof since 1997.',
    gstin: '37AABCP3021P1ZR',
    pan: 'AABCP3021P',
    town: 'ponnur',
    addressLine: '5-9-2, Bapatla Road, Ponnur',
    pincode: '522124',
    phone: '+919848030021',
    email: 'owner@ponnurmotorworks.in',
    landline: '08643 24 3021',
    ownerName: 'V. Krishna Murthy',
    establishedYear: 1997,
    specialities: ['Workshop on site', 'Sedans', 'Diesel'],
    medianResponseMins: 40,
  },
  {
    brandName: 'Ponnur Car Point',
    legalName: 'Ponnur Car Point Enterprises',
    tagline: 'A first car, and the licence to go with it.',
    gstin: '37AACFP3022Q1ZS',
    pan: 'AACFP3022Q',
    town: 'ponnur',
    addressLine: '2-40, Market Street, Ponnur',
    pincode: '522124',
    phone: '+919848030022',
    email: 'sales@ponnurcarpoint.in',
    landline: '08643 24 3022',
    ownerName: 'G. Vijaya Lakshmi',
    establishedYear: 2021,
    specialities: ['First-time buyers', 'Hatchbacks', 'Petrol'],
    medianResponseMins: 9,
  },

  // ── Kurnool district ──────────────────────────────────────────────────────
  {
    brandName: 'Tungabhadra Motors',
    legalName: 'Tungabhadra Motors Pvt Ltd',
    tagline: 'Rayalaseema stock, priced without theatre.',
    gstin: '37AAEFT3023R1ZT',
    pan: 'AAEFT3023R',
    town: 'kurnool',
    addressLine: '40-118, Park Road, Kurnool',
    pincode: '518001',
    phone: '+919848030023',
    email: 'contact@tungabhadramotors.in',
    landline: '08518 22 3023',
    ownerName: 'C. Obulesu',
    establishedYear: 2012,
    specialities: ['Fixed price', 'Sedans', 'Hatchbacks'],
    medianResponseMins: 32,
  },
  {
    brandName: 'Kurnool Auto Bazaar',
    legalName: 'Kurnool Auto Bazaar LLP',
    tagline: 'Air conditioning that works, in this heat.',
    gstin: '37AAFCK3024S1ZU',
    pan: 'AAFCK3024S',
    town: 'kurnool',
    addressLine: '52-6-14, Bellary Road, Kurnool',
    pincode: '518002',
    phone: '+919848030024',
    email: 'desk@kurnoolautobazaar.in',
    landline: '08518 22 3024',
    ownerName: 'Sk. Nayeem Basha',
    establishedYear: 2016,
    specialities: ['Pre-delivery inspection', 'Petrol', 'Exchange'],
    medianResponseMins: 18,
  },
  {
    brandName: 'Nandyal Road Cars',
    legalName: 'Nandyal Road Cars Enterprises',
    tagline: 'Long-distance sedans for long-distance roads.',
    gstin: '37AAGFN3025T1ZV',
    pan: 'AAGFN3025T',
    town: 'kurnool',
    addressLine: '9-88, Nandyal Road, Kurnool',
    pincode: '518004',
    phone: '+919848030025',
    email: 'hello@nandyalroadcars.in',
    landline: '08518 23 3025',
    ownerName: 'D. Ravindra Reddy',
    establishedYear: 2020,
    specialities: ['Highway cars', 'Diesel', 'Sedans'],
    medianResponseMins: null,
  },
  {
    brandName: 'Adoni Cotton Belt Autos',
    legalName: 'Adoni Cotton Belt Autos Pvt Ltd',
    tagline: 'Ginning-season prices, all year round.',
    gstin: '37AABCA3026U1ZW',
    pan: 'AABCA3026U',
    town: 'adoni',
    addressLine: '3-2-40, Ginning Factory Road, Adoni',
    pincode: '518301',
    phone: '+919848030026',
    email: 'owner@adonicottonbeltautos.in',
    landline: '08512 25 3026',
    ownerName: 'M. Hanumantha Rao',
    establishedYear: 2015,
    specialities: ['Fixed price', 'MUVs', 'Commercial vehicles'],
    medianResponseMins: 37,
  },
  {
    brandName: 'Adoni Motor Traders',
    legalName: 'Adoni Motor Traders LLP',
    tagline: 'Karnataka plates, Andhra paperwork, both fine.',
    gstin: '37AACFA3027V1ZX',
    pan: 'AACFA3027V',
    town: 'adoni',
    addressLine: '1-14-9, Bellary Road, Adoni',
    pincode: '518301',
    phone: '+919848030027',
    email: 'sales@adonimotortraders.in',
    landline: '08512 25 3027',
    ownerName: 'K. Anjaneyulu',
    establishedYear: 2018,
    specialities: ['Inter-state transfer', 'RC transfer', 'Sedans'],
    medianResponseMins: 24,
  },
  {
    brandName: 'Adoni Star Motors',
    legalName: 'Adoni Star Motors Enterprises',
    tagline: 'Four cars, four honest histories.',
    gstin: '37AAEFA3028W1ZY',
    pan: 'AAEFA3028W',
    town: 'adoni',
    addressLine: '5-6-1, Old Bus Stand Road, Adoni',
    pincode: '518302',
    phone: '+919848030028',
    email: 'contact@adonistarmotors.in',
    landline: '08512 26 3028',
    ownerName: 'S. Peera Sab',
    establishedYear: 2022,
    specialities: ['Single-owner cars', 'Hatchbacks', 'Budget cars'],
    medianResponseMins: 15,
  },
  {
    brandName: 'Yemmiganur Auto Yard',
    legalName: 'Yemmiganur Auto Yard Pvt Ltd',
    tagline: 'The mill town yard since 2005.',
    gstin: '37AAFCY3029X1ZA',
    pan: 'AAFCY3029X',
    town: 'yemmiganur',
    addressLine: '7-2-30, Cooperative Colony, Yemmiganur',
    pincode: '518360',
    phone: '+919848030029',
    email: 'desk@yemmiganurautoyard.in',
    landline: '08512 27 3029',
    ownerName: 'P. Chennaiah',
    establishedYear: 2005,
    specialities: ['Finance assistance', 'Budget cars', 'Hatchbacks'],
    medianResponseMins: 48,
  },
  {
    brandName: 'Yemmiganur Car Company',
    legalName: 'Yemmiganur Car Company LLP',
    tagline: 'CNG, since the pump opened.',
    gstin: '37AAGFY3030Y1ZB',
    pan: 'AAGFY3030Y',
    town: 'yemmiganur',
    addressLine: '2-9-14, Adoni Road, Yemmiganur',
    pincode: '518360',
    phone: '+919848030030',
    email: 'hello@yemmiganurcarcompany.in',
    landline: '08512 27 3030',
    ownerName: 'B. Sunitha',
    establishedYear: 2021,
    specialities: ['CNG', 'Petrol', 'First-time buyers'],
    medianResponseMins: 10,
  },

  // ══ Kerala ════════════════════════════════════════════════════════════════

  // ── Ernakulam district ────────────────────────────────────────────────────
  {
    brandName: 'Marine Drive Motors',
    legalName: 'Marine Drive Motors Pvt Ltd',
    tagline: 'Backwater city, rust-checked cars.',
    gstin: '32AABCM4001C1ZD',
    pan: 'AABCM4001C',
    town: 'kochi',
    addressLine: '39/2, Shanmugham Road, Marine Drive',
    pincode: '682031',
    phone: '+919847040001',
    email: 'owner@marinedrivemotors.in',
    landline: '0484 235 4001',
    ownerName: 'Thomas Varghese',
    establishedYear: 2008,
    specialities: ['Pre-delivery inspection', 'Sedans', 'Single-owner cars'],
    medianResponseMins: 14,
  },
  {
    brandName: 'Kaloor Car Company',
    legalName: 'Kaloor Car Company LLP',
    tagline: 'Automatics and hybrids, city-driven.',
    gstin: '32AACFK4002D1ZE',
    pan: 'AACFK4002D',
    town: 'kochi',
    addressLine: '18/1140, Kaloor–Kadavanthra Road',
    pincode: '682017',
    phone: '+919847040002',
    email: 'sales@kaloorcarcompany.in',
    landline: '0484 234 4002',
    ownerName: 'Anitha Nair',
    establishedYear: 2016,
    specialities: ['Automatics', 'Hybrid', 'Hatchbacks'],
    medianResponseMins: 19,
  },
  {
    brandName: 'Vyttila Auto Hub',
    legalName: 'Vyttila Auto Hub and Finance',
    tagline: 'NRI paperwork, done properly.',
    gstin: '32AAEFV4003E1ZF',
    pan: 'AAEFV4003E',
    town: 'kochi',
    addressLine: '55/300, Vyttila Junction, Ernakulam',
    pincode: '682019',
    phone: '+919847040003',
    email: 'contact@vyttilaautohub.in',
    landline: '0484 230 4003',
    ownerName: 'Abdul Latheef K',
    establishedYear: 2012,
    specialities: ['NRI buyers', 'Finance assistance', 'Sedans'],
    medianResponseMins: 27,
  },
  {
    brandName: 'Fort Kochi Classics',
    legalName: 'Fort Kochi Classics Pvt Ltd',
    tagline: 'Older cars, kept the way they were meant to be.',
    gstin: '32AAFCF4004F1ZG',
    pan: 'AAFCF4004F',
    town: 'kochi',
    addressLine: '1/436, Bazaar Road, Fort Kochi',
    pincode: '682001',
    phone: '+919847040004',
    email: 'desk@fortkochiclassics.in',
    landline: '0484 221 4004',
    ownerName: 'Joseph Fernandez',
    establishedYear: 2014,
    specialities: ['Classic cars', 'Reconditioned', 'Valuation'],
    medianResponseMins: null,
  },
  {
    brandName: 'Aluva Junction Autos',
    legalName: 'Aluva Junction Autos LLP',
    tagline: 'Airport road, open till the last flight.',
    gstin: '32AAGFA4005G1ZH',
    pan: 'AAGFA4005G',
    town: 'aluva',
    addressLine: '7/210, Bank Junction, Aluva',
    pincode: '683101',
    phone: '+919847040005',
    email: 'hello@aluvajunctionautos.in',
    landline: '0484 262 4005',
    ownerName: 'Rajeev Menon',
    establishedYear: 2018,
    specialities: ['NRI buyers', 'Late hours', 'Compact SUVs'],
    medianResponseMins: 12,
  },
  {
    brandName: 'Periyar Motors',
    legalName: 'Periyar Motors Enterprises',
    tagline: 'Flood-history disclosed, every single car.',
    gstin: '32AABCP4006H1ZJ',
    pan: 'AABCP4006H',
    town: 'aluva',
    addressLine: '3/88, Marthanda Varma Bridge Road, Aluva',
    pincode: '683101',
    phone: '+919847040006',
    email: 'owner@periyarmotors.in',
    landline: '0484 262 4006',
    ownerName: 'Sunil Kumar P',
    establishedYear: 2019,
    specialities: ['Pre-delivery inspection', 'Hatchbacks', 'Petrol'],
    medianResponseMins: 21,
  },
  {
    brandName: 'Desom Car Point',
    legalName: 'Desom Car Point Pvt Ltd',
    tagline: 'Under five lakh, all of it road-tested.',
    gstin: '32AACFD4007J1ZK',
    pan: 'AACFD4007J',
    town: 'aluva',
    addressLine: '11/4, Desom, Aluva',
    pincode: '683102',
    phone: '+919847040007',
    email: 'sales@desomcarpoint.in',
    landline: '0484 263 4007',
    ownerName: 'Bindu Thomas',
    establishedYear: 2021,
    specialities: ['Budget cars', 'First-time buyers', 'Hatchbacks'],
    medianResponseMins: 33,
  },
  {
    brandName: 'Perumbavoor Auto Traders',
    legalName: 'Perumbavoor Auto Traders LLP',
    tagline: 'Timber-town pickups and load carriers.',
    gstin: '32AAEFP4008K1ZL',
    pan: 'AAEFP4008K',
    town: 'perumbavoor',
    addressLine: '5/90, Kothamangalam Road, Perumbavoor',
    pincode: '683542',
    phone: '+919847040008',
    email: 'contact@perumbavoorautotraders.in',
    landline: '0484 259 4008',
    ownerName: 'Shajahan M A',
    establishedYear: 2011,
    specialities: ['Commercial vehicles', 'Diesel', 'Fleet buyers'],
    medianResponseMins: 45,
  },
  {
    brandName: 'Rayonpuram Motors',
    legalName: 'Rayonpuram Motors Enterprises',
    tagline: 'Family cars, and time to decide about them.',
    gstin: '32AAFCR4009L1ZM',
    pan: 'AAFCR4009L',
    town: 'perumbavoor',
    addressLine: '2/33, Rayonpuram, Perumbavoor',
    pincode: '683542',
    phone: '+919847040009',
    email: 'desk@rayonpurammotors.in',
    landline: '0484 259 4009',
    ownerName: 'Elizabeth Kurian',
    establishedYear: 2017,
    specialities: ['MUVs', 'Seven-seaters', 'Exchange'],
    medianResponseMins: 28,
  },
  {
    brandName: 'Muvattupuzha Car Bazaar',
    legalName: 'Muvattupuzha Car Bazaar Pvt Ltd',
    tagline: 'Three rivers, one honest yard, since 2003.',
    gstin: '32AAGFM4010M1ZN',
    pan: 'AAGFM4010M',
    town: 'muvattupuzha',
    addressLine: '9/141, Kothamangalam Road, Muvattupuzha',
    pincode: '686661',
    phone: '+919847040010',
    email: 'hello@muvattupuzhacarbazaar.in',
    landline: '0485 282 4010',
    ownerName: 'Mathew Chacko',
    establishedYear: 2003,
    specialities: ['Sedans', 'Single-owner cars', 'Valuation'],
    medianResponseMins: 38,
  },
  {
    brandName: 'Vazhakulam Autos',
    legalName: 'Vazhakulam Autos LLP',
    tagline: 'Hill-road diesels for the high range.',
    gstin: '32AABCV4011N1ZP',
    pan: 'AABCV4011N',
    town: 'muvattupuzha',
    addressLine: '4/17, Vazhakulam Junction, Muvattupuzha',
    pincode: '686670',
    phone: '+919847040011',
    email: 'owner@vazhakulamautos.in',
    landline: '0485 282 4011',
    ownerName: 'Faisal Rawther',
    establishedYear: 2015,
    specialities: ['SUVs', 'Diesel', 'Pre-delivery inspection'],
    medianResponseMins: 23,
  },

  // ── Thrissur district ─────────────────────────────────────────────────────
  {
    brandName: 'Round South Motors',
    legalName: 'Round South Motors Pvt Ltd',
    tagline: 'On the Round since 2001.',
    gstin: '32AACFR4012P1ZQ',
    pan: 'AACFR4012P',
    town: 'thrissur',
    addressLine: '26/818, Round South, Thrissur',
    pincode: '680001',
    phone: '+919847040012',
    email: 'sales@roundsouthmotors.in',
    landline: '0487 242 4012',
    ownerName: 'Ravi Menon',
    establishedYear: 2001,
    specialities: ['Sedans', 'Hatchbacks', 'Valuation'],
    medianResponseMins: 20,
  },
  {
    brandName: 'Gold Souk Cars',
    legalName: 'Gold Souk Cars and Credits',
    tagline: 'Gold-loan finance, if that is the easier route.',
    gstin: '32AAEFG4013Q1ZR',
    pan: 'AAEFG4013Q',
    town: 'thrissur',
    addressLine: '13/220, High Road, Thrissur',
    pincode: '680001',
    phone: '+919847040013',
    email: 'contact@goldsoukcars.in',
    landline: '0487 242 4013',
    ownerName: 'Sreekumar T V',
    establishedYear: 2013,
    specialities: ['Finance assistance', 'Automatics', 'Sedans'],
    medianResponseMins: 16,
  },
  {
    brandName: 'Poothole Auto Yard',
    legalName: 'Poothole Auto Yard LLP',
    tagline: 'Small cars, small prices, no drama.',
    gstin: '32AAFCP4014R1ZS',
    pan: 'AAFCP4014R',
    town: 'thrissur',
    addressLine: '8/71, Poothole Road, Thrissur',
    pincode: '680004',
    phone: '+919847040014',
    email: 'desk@pootholeautoyard.in',
    landline: '0487 244 4014',
    ownerName: 'Deepa Krishnan',
    establishedYear: 2020,
    specialities: ['Budget cars', 'Petrol', 'First-time buyers'],
    medianResponseMins: 30,
  },
  {
    brandName: 'Chalakudy Car House',
    legalName: 'Chalakudy Car House Enterprises',
    tagline: 'On the national highway, open all seven days.',
    gstin: '32AAGFC4015S1ZT',
    pan: 'AAGFC4015S',
    town: 'chalakudy',
    addressLine: '6/44, NH-544, Chalakudy',
    pincode: '680307',
    phone: '+919847040015',
    email: 'hello@chalakudycarhouse.in',
    landline: '0480 270 4015',
    ownerName: 'Jose Antony',
    establishedYear: 2016,
    specialities: ['Fixed price', 'Compact SUVs', 'Exchange'],
    medianResponseMins: 25,
  },
  {
    brandName: 'Athirappilly Road Autos',
    legalName: 'Athirappilly Road Autos Pvt Ltd',
    tagline: 'Tourist-route SUVs, hard-checked.',
    gstin: '32AABCA4016T1ZU',
    pan: 'AABCA4016T',
    town: 'chalakudy',
    addressLine: '2/9, Athirappilly Road, Chalakudy',
    pincode: '680307',
    phone: '+919847040016',
    email: 'owner@athirappillyroadautos.in',
    landline: '0480 270 4016',
    ownerName: 'Prasad Nambiar',
    establishedYear: 2012,
    specialities: ['SUVs', 'MUVs', 'Commercial vehicles'],
    medianResponseMins: 43,
  },
  {
    brandName: 'Koratty Motor Traders',
    legalName: 'Koratty Motor Traders LLP',
    tagline: 'Ex-company cars from the infopark side.',
    gstin: '32AACFK4017U1ZV',
    pan: 'AACFK4017U',
    town: 'chalakudy',
    addressLine: '10/3, Koratty, Chalakudy',
    pincode: '680308',
    phone: '+919847040017',
    email: 'sales@korattymotortraders.in',
    landline: '0480 271 4017',
    ownerName: 'Nisha Paul',
    establishedYear: 2019,
    specialities: ['Fleet buyers', 'Sedans', 'Single-owner cars'],
    medianResponseMins: 11,
  },
  {
    brandName: 'Irinjalakuda Auto Centre',
    legalName: 'Irinjalakuda Auto Centre and Workshop',
    tagline: 'Sold here, serviced here, since 1998.',
    gstin: '32AAEFI4018V1ZW',
    pan: 'AAEFI4018V',
    town: 'irinjalakuda',
    addressLine: '4/61, Thrissur Road, Irinjalakuda',
    pincode: '680121',
    phone: '+919847040018',
    email: 'contact@irinjalakudaautocentre.in',
    landline: '0480 282 4018',
    ownerName: 'Varghese Paulose',
    establishedYear: 1998,
    specialities: ['Workshop on site', 'Sedans', 'Extended warranty'],
    medianResponseMins: 34,
  },
  {
    brandName: 'Koodalmanikyam Cars',
    legalName: 'Koodalmanikyam Cars Pvt Ltd',
    tagline: 'Temple-town yard, festival-season stock.',
    gstin: '32AAFCK4019W1ZX',
    pan: 'AAFCK4019W',
    town: 'irinjalakuda',
    addressLine: '1/18, West Nada, Irinjalakuda',
    pincode: '680121',
    phone: '+919847040019',
    email: 'desk@koodalmanikyamcars.in',
    landline: '0480 282 4019',
    ownerName: 'Radhika Menon',
    establishedYear: 2017,
    specialities: ['MUVs', 'Hatchbacks', 'Exchange'],
    medianResponseMins: 18,
  },
  {
    brandName: 'Kallettumkara Autos',
    legalName: 'Kallettumkara Autos Enterprises',
    tagline: 'Two cars a week, both of them known.',
    gstin: '32AAGFK4020X1ZY',
    pan: 'AAGFK4020X',
    town: 'irinjalakuda',
    addressLine: '7/2, Kallettumkara, Irinjalakuda',
    pincode: '680683',
    phone: '+919847040020',
    email: 'hello@kallettumkaraautos.in',
    landline: '0480 283 4020',
    ownerName: 'Baby John',
    establishedYear: 2013,
    specialities: ['Single-owner cars', 'Hatchbacks', 'Valuation'],
    medianResponseMins: null,
  },
  {
    brandName: 'Kunnamkulam Motor Mart',
    legalName: 'Kunnamkulam Motor Mart Pvt Ltd',
    tagline: 'The trading town does cars too.',
    gstin: '32AABCK4021Y1ZA',
    pan: 'AABCK4021Y',
    town: 'kunnamkulam',
    addressLine: '12/40, Guruvayur Road, Kunnamkulam',
    pincode: '680503',
    phone: '+919847040021',
    email: 'owner@kunnamkulammotormart.in',
    landline: '04885 22 4021',
    ownerName: 'Muhammed Rafi',
    establishedYear: 2009,
    specialities: ['Fixed price', 'Sedans', 'Exchange'],
    medianResponseMins: 29,
  },
  {
    brandName: 'Arthat Auto Point',
    legalName: 'Arthat Auto Point LLP',
    tagline: 'First cars for a town that walks everywhere.',
    gstin: '32AACFA4022Z1ZB',
    pan: 'AACFA4022Z',
    town: 'kunnamkulam',
    addressLine: '3/7, Arthat Road, Kunnamkulam',
    pincode: '680503',
    phone: '+919847040022',
    email: 'sales@arthatautopoint.in',
    landline: '04885 22 4022',
    ownerName: 'Shiny Joseph',
    establishedYear: 2022,
    specialities: ['First-time buyers', 'Petrol', 'Hatchbacks'],
    medianResponseMins: 7,
  },

  // ── Kozhikode district ────────────────────────────────────────────────────
  {
    brandName: 'Mananchira Motors',
    legalName: 'Mananchira Motors Pvt Ltd',
    tagline: 'City-centre yard, twenty years of it.',
    gstin: '32AAEFM4023A1ZC',
    pan: 'AAEFM4023A',
    town: 'kozhikode',
    addressLine: '17/380, Mananchira Square, Kozhikode',
    pincode: '673001',
    phone: '+919847040023',
    email: 'contact@mananchiramotors.in',
    landline: '0495 236 4023',
    ownerName: 'K P Abdul Salam',
    establishedYear: 2005,
    specialities: ['Sedans', 'Automatics', 'Valuation'],
    medianResponseMins: 22,
  },
  {
    brandName: 'Beach Road Car Company',
    legalName: 'Beach Road Car Company LLP',
    tagline: 'Gulf-return buyers, and the paperwork they need.',
    gstin: '32AAFCB4024B1ZD',
    pan: 'AAFCB4024B',
    town: 'kozhikode',
    addressLine: '5/112, Beach Road, Kozhikode',
    pincode: '673032',
    phone: '+919847040024',
    email: 'desk@beachroadcarcompany.in',
    landline: '0495 237 4024',
    ownerName: 'Noushad Ali',
    establishedYear: 2014,
    specialities: ['NRI buyers', 'RC transfer', 'Compact SUVs'],
    medianResponseMins: 13,
  },
  {
    brandName: 'Wayanad Road Autos',
    legalName: 'Wayanad Road Autos Enterprises',
    tagline: 'Anything that has to climb the Thamarassery ghat.',
    gstin: '32AAGFW4025C1ZE',
    pan: 'AAGFW4025C',
    town: 'kozhikode',
    addressLine: '9/64, Wayanad Road, Kozhikode',
    pincode: '673008',
    phone: '+919847040025',
    email: 'hello@wayanadroadautos.in',
    landline: '0495 238 4025',
    ownerName: 'Sajeev Kumar V',
    establishedYear: 2018,
    specialities: ['SUVs', 'Diesel', 'Pre-delivery inspection'],
    medianResponseMins: 36,
  },
  {
    brandName: 'Vadakara Auto Traders',
    legalName: 'Vadakara Auto Traders Pvt Ltd',
    tagline: 'Coast-road yard, honest about the salt.',
    gstin: '32AABCV4026D1ZF',
    pan: 'AABCV4026D',
    town: 'vadakara',
    addressLine: '6/230, NH-66, Vadakara',
    pincode: '673101',
    phone: '+919847040026',
    email: 'owner@vadakaraautotraders.in',
    landline: '0496 252 4026',
    ownerName: 'P Balakrishnan',
    establishedYear: 2010,
    specialities: ['Reconditioned', 'Hatchbacks', 'Single-owner cars'],
    medianResponseMins: 26,
  },
  {
    brandName: 'Lokanarkavu Cars',
    legalName: 'Lokanarkavu Cars LLP',
    tagline: 'Family yard, third generation on it.',
    gstin: '32AACFL4027E1ZG',
    pan: 'AACFL4027E',
    town: 'vadakara',
    addressLine: '2/18, Lokanarkavu Road, Vadakara',
    pincode: '673104',
    phone: '+919847040027',
    email: 'sales@lokanarkavucars.in',
    landline: '0496 252 4027',
    ownerName: 'Vinod Krishnan',
    establishedYear: 2015,
    specialities: ['Sedans', 'Valuation', 'Exchange'],
    medianResponseMins: 17,
  },
  {
    brandName: 'Mahe Border Motors',
    legalName: 'Mahe Border Motors Enterprises',
    tagline: 'Two territories, one paperwork desk.',
    gstin: '32AAEFM4028F1ZH',
    pan: 'AAEFM4028F',
    town: 'vadakara',
    addressLine: '11/5, Mahe Road, Vadakara',
    pincode: '673101',
    phone: '+919847040028',
    email: 'contact@mahebordermotors.in',
    landline: '0496 253 4028',
    ownerName: 'Ashraf Puthiyapurayil',
    establishedYear: 2020,
    specialities: ['Inter-state transfer', 'RC transfer', 'Budget cars'],
    medianResponseMins: 41,
  },
  {
    brandName: 'Koyilandy Car Point',
    legalName: 'Koyilandy Car Point Pvt Ltd',
    tagline: 'Harbour-town stock, weekday prices.',
    gstin: '32AAFCK4029G1ZJ',
    pan: 'AAFCK4029G',
    town: 'koyilandy',
    addressLine: '8/40, Harbour Road, Koyilandy',
    pincode: '673305',
    phone: '+919847040029',
    email: 'desk@koyilandycarpoint.in',
    landline: '0496 262 4029',
    ownerName: 'Rasheed Kunhi',
    establishedYear: 2016,
    specialities: ['Budget cars', 'Commercial vehicles', 'Exchange'],
    medianResponseMins: 32,
  },
  {
    brandName: 'Quilandy Auto Mart',
    legalName: 'Quilandy Auto Mart LLP',
    tagline: 'Automatics for the highway crawl.',
    gstin: '32AAGFQ4030H1ZK',
    pan: 'AAGFQ4030H',
    town: 'koyilandy',
    addressLine: '3/91, NH-66, Koyilandy',
    pincode: '673305',
    phone: '+919847040030',
    email: 'hello@quilandyautomart.in',
    landline: '0496 262 4030',
    ownerName: 'Fathima Beevi',
    establishedYear: 2021,
    specialities: ['Automatics', 'Petrol', 'Compact SUVs'],
    medianResponseMins: 15,
  },
];

/**
 * The seed rows, with the town flattened in and the three derived columns built.
 *
 * `slug` is **derived rather than written**, through the same `dealerSlug` the
 * registration path uses. A hundred and twenty hand-typed slugs were a hundred
 * and twenty chances for the seed to disagree with the function that produces
 * every real one — and the disagreement would be invisible, because a
 * hand-typed slug is a perfectly valid slug. Deriving it means correcting a
 * town in `TOWNS` corrects the addresses that follow from it, in the URL and in
 * the bucket, without anybody remembering to.
 *
 * `mapsUrl` is composed here rather than stored per dealer because these pins
 * are the town's, not the yard's — a real dealer pastes their own Share link at
 * onboarding, and inventing a hundred and twenty distinct `maps.app.goo.gl`
 * short codes would be inventing links that resolve to nothing.
 */
export const DEV_DEALERS: DevDealerRow[] = DEALERS.map((dealer, index) => {
  const town = TOWNS[dealer.town];
  return {
    ...dealer,
    ...town,
    slug: dealerSlug({
      legalName: dealer.legalName,
      city: town.city,
      district: town.district,
      state: town.state,
    }),
    mapsUrl: `https://www.google.com/maps/search/?api=1&query=${String(town.lat)},${String(town.lng)}`,
    workingHours: hoursFor(index),
  };
});
