export const ENQUIRY_DETAIL_TEXT = {
  back: '← All enquiries',
  title: (name: string) => `Enquiry from ${name}`,
  metaTitle: 'Enquiry',
  received: (label: string) => `Received ${label} IST`,
  readOnly:
    'Read-only. The dealership changes this enquiry’s status from its own inbox; nothing on this page changes it.',
  customerSees: 'Customer sees',
  customer: 'Customer',
  name: 'Name',
  mobile: 'Mobile',
  verified: 'Verified',
  noNumber: 'No number on file',
  memberSince: 'Customer since',
  vehicle: 'Vehicle',
  plate: 'Registration',
  listingStatus: 'Listing status',
  listingId: 'Listing ID',
  noPhoto: 'No photograph yet',
  openListing: 'Open listing review',
  openPublic: 'View on Dealers-Drive',
  notPublic: 'Not on the marketplace now',
  dealer: 'Dealer',
  dealerStatus: 'Dealership status',
  location: 'Location',
  dealerPhone: 'Contact number',
  notEntered: 'Not entered',
  openDealer: 'Open dealer',
  dealerEnquiries: 'All their enquiries',
  enquiry: 'Enquiry',
  message: 'Message',
  noMessage: 'No message — the customer asked to be contacted.',
  status: 'Status',
  sent: 'Sent',
  contacted: 'First contacted',
  closed: 'Closed',
  history: 'History',
  historyIntro: 'Recorded whenever the enquiry was sent or the dealership changed its status.',
  noHistory: 'No recorded history for this enquiry.',
  transition: (from: string, to: string) => `${from} → ${to}`,
  by: (actor: string) => `by ${actor}`,
  timesInIst: 'All times IST.',
  tickets: 'Support tickets',
  ticketsIntro: 'Requests the customer raised with Dealers-Drive about this enquiry.',
  noTickets: 'No support tickets reference this enquiry.',
} as const;
