import type {
  PublicStorefrontDto,
  StorefrontInventoryResponse,
  StorefrontVehicleResponse,
  VehicleCardDto,
} from '@dealers-drive/contracts';

export const SITE: PublicStorefrontDto = {
  name: 'Alpha Motors',
  legalName: 'Alpha Motors Limited',
  theme: 'LIGHT',
  accentColor: '#155e75',
  headline: 'A car for your next chapter',
  description: 'Explore our dealership inventory in Vellore.',
  about: 'Visit our synthetic test yard to see our available cars.',
  address: 'Synthetic test yard, Vellore, Tamil Nadu',
  city: 'Vellore',
  contactPhone: '+919840099991',
  whatsappPhone: '+919840099991',
  mapsUrl: 'https://www.google.com/maps?q=Vellore',
  socialUrls: ['https://www.instagram.com/alpha'],
  logoUrl: null,
  heroUrl: '/test-yard.webp',
  yardUrls: ['/test-yard.webp'],
  primaryHostname: 'alpha.example.com',
  requestedHostname: 'alpha.example.com',
  seoTitle: 'Alpha Motors',
  seoDescription: 'Approved dealership inventory',
  isVerified: true,
  updatedAt: '2026-10-08T00:00:00Z',
};
export const CARD: VehicleCardDto = {
  slug: 'honda-city',
  availability: 'AVAILABLE',
  title: '2023 Honda City',
  year: 2023,
  priceLabel: '₹8,50,000',
  metaLabel: '15,000 km · Petrol · Manual · Vellore',
  image: { url: '/car.webp', alt: 'Honda City exterior' },
  imageCount: 2,
  dealer: { name: 'Alpha Motors', slug: 'alpha-motors', initials: 'AM', isVerified: true },
};
export const INVENTORY: StorefrontInventoryResponse = {
  data: [
    CARD,
    { ...CARD, slug: 'reserved-car', title: 'Reserved Honda City', availability: 'RESERVED' },
  ],
  page: { page: 1, limit: 24, total: 2, totalPages: 1 },
};
export const CAR: StorefrontVehicleResponse = {
  slug: CARD.slug,
  title: CARD.title,
  availability: 'AVAILABLE',
  year: 2023,
  priceLabel: CARD.priceLabel,
  negotiabilityLabel: null,
  summary: 'Petrol · Manual · 15,000 km',
  description: 'Synthetic test vehicle description.',
  specs: [
    { label: 'Fuel', value: 'Petrol' },
    { label: 'Transmission', value: 'Manual' },
  ],
  images: [
    { url: '/car.webp', alt: 'Honda City exterior' },
    { url: '/interior.webp', alt: 'Honda City interior' },
  ],
  primaryIndex: 0,
  publishedLabel: 'Published 8 Oct',
  facts: {
    make: 'Honda',
    model: 'City',
    variant: null,
    bodyType: 'Sedan',
    fuelType: 'Petrol',
    transmission: 'Manual',
    color: 'White',
    kilometersDriven: 15000,
    ownerCount: 1,
    pricePaise: 85000000,
  },
  dealer: {
    name: 'Alpha Motors',
    slug: 'alpha-motors',
    initials: 'AM',
    isVerified: true,
    location: 'Vellore',
    city: 'Vellore',
    district: 'Vellore',
    state: 'Tamil Nadu',
  },
};
