/**
 * The searchable component index — this is what "search the sandbox first"
 * actually means.
 *
 * Discovery failure is the problem this repository has, measurably: `<Button>`
 * is used 29 times against 88 raw `className="btn …"` sites, a 75 % bypass
 * rate, and `.table` was hand-rolled in five separate pages. Nobody set out to
 * duplicate anything — they could not find what already existed.
 *
 * So every entry carries `aliases`. `dealer-card.tsx` exports `DirectoryCard`,
 * and somebody looking for "DealerCard" must still find it (finding D-6).
 */
export type Category =
  'Primitives' | 'Forms' | 'Vehicle' | 'Dealer' | 'Search' | 'Console' | 'Admin' | 'Layout';

export type Ownership =
  'Primitive' | 'Shared' | 'Feature-shared' | 'Feature-specific' | 'Page-specific';

export interface RegistryEntry {
  /** The component-map id, e.g. 'C032'. */
  id: string;
  name: string;
  /** Repository-relative path to the real component. */
  source: string;
  category: Category;
  ownership: Ownership;
  /** One line. What it is for, not what it looks like. */
  purpose: string;
  /** Every name someone might plausibly search for. The D-6 fix. */
  aliases: string[];
  /** F-numbers that render it. */
  features: string[];
  props: string[];
  states: string[];
  reusable: boolean;
  /** Storybook id, for deep links. */
  storyId: string;
}

/**
 * Populated one component at a time, by the feature that brings the component
 * across. An entry without a story, or a story without an entry, is a gap —
 * see `docs/project/component-sandbox.md` §5.
 */
export const registry: RegistryEntry[] = [
  {
    id: 'C001',
    name: 'Button',
    source: 'apps/web/src/components/ui/button.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Every action in the product. 5 variants x 5 sizes, block, loading.',
    aliases: ['Btn', 'CTA', 'SubmitButton', 'ActionButton', 'btn'],
    features: ['F009'],
    props: ['variant', 'size', 'block', 'loading', 'disabled', 'children'],
    states: ['default', 'hover', 'active', 'disabled', 'loading', 'block'],
    reusable: true,
    storyId: 'primitives-button',
  },
  {
    id: 'C002',
    name: 'ButtonLink',
    source: 'apps/web/src/components/ui/button.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'A Button that navigates — an anchor, so middle-click still works.',
    aliases: ['LinkButton', 'AnchorButton', 'NavButton'],
    features: ['F009'],
    props: ['href', 'variant', 'size', 'block', 'children'],
    states: ['default', 'hover', 'active'],
    reusable: true,
    storyId: 'primitives-button--as-link',
  },
  {
    id: 'C003',
    name: 'Plate',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'The registration plate. The signature element, in exactly four places.',
    aliases: ['RegistrationPlate', 'NumberPlate', 'YearBadge', 'VerifiedChip', 'dd-plate'],
    features: ['F009'],
    props: ['size', 'children'],
    states: ['year', 'logo', 'chip', 'marker'],
    reusable: true,
    storyId: 'primitives-plate',
  },
  {
    id: 'C004',
    name: 'StatusTag',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'A status badge. Never colour alone — the label always carries the meaning.',
    aliases: ['StatusBadge', 'StatusChip', 'Pill', 'tag-ok', 'tag-err'],
    features: ['F010'],
    props: ['tone', 'children'],
    states: ['ok', 'warn', 'err', 'neutral', 'accent'],
    reusable: true,
    storyId: 'primitives-statustag',
  },
  {
    id: 'C005',
    name: 'Tag',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'The non-status sibling of StatusTag. Three variants, no semantics.',
    aliases: ['Chip', 'Label', 'Badge', 'tag-neutral', 'tag-outline'],
    features: ['F010'],
    props: ['variant', 'children'],
    states: ['neutral', 'accent', 'outline'],
    reusable: true,
    storyId: 'primitives-statustag--tag-variants',
  },
  {
    id: 'C006',
    name: 'Banner',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Inline page-level message. The most-imported component in the product.',
    aliases: ['Alert', 'Notice', 'Callout', 'InlineMessage', 'Toast'],
    features: ['F010'],
    props: ['tone', 'title', 'children', 'action'],
    states: ['ok', 'warn', 'err', 'title-only', 'body-only', 'with-action', 'long-text'],
    reusable: true,
    storyId: 'primitives-statustag--banner-tones',
  },
  {
    id: 'C007',
    name: 'Blueprint',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'The framed panel. All four registration marks, always (DESIGN-SPEC 4.4).',
    aliases: ['Frame', 'Panel', 'BlueprintFrame', 'Corners', 'blueprint'],
    features: ['F011'],
    props: ['as', 'className', 'children'],
    states: ['div', 'section', 'article'],
    reusable: true,
    storyId: 'primitives-structure--blueprint-frame',
  },
  {
    id: 'C008',
    name: 'Avatar',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Initials tile for a person. Decorative — aria-hidden.',
    aliases: ['UserAvatar', 'Initials', 'ProfilePic', 'Gravatar'],
    features: ['F011'],
    props: ['initials', 'size'],
    states: ['20px', '22px', '1-3 letters'],
    reusable: true,
    storyId: 'primitives-structure--identity-tiles',
  },
  {
    id: 'C009',
    name: 'LogoTile',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Initials tile for a dealership. The bordered sibling of Avatar.',
    aliases: ['DealerLogo', 'BrandTile', 'Logo', 'Initials'],
    features: ['F011'],
    props: ['initials', 'size'],
    states: ['42px', '44px', '1-3 letters'],
    reusable: true,
    storyId: 'primitives-structure--identity-tiles',
  },
  {
    id: 'C010',
    name: 'StatCard',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'A labelled number with an optional toned delta.',
    aliases: ['Stat', 'Metric', 'KpiCard', 'CounterCard'],
    features: ['F011'],
    props: ['label', 'value', 'delta', 'deltaTone'],
    states: ['ok', 'warn', 'err', 'neutral', 'no-delta', 'long-value'],
    reusable: true,
    storyId: 'primitives-structure--stats',
  },
  {
    id: 'C011',
    name: 'ImageSlot',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Placeholder panel naming the shot, when a vehicle has no photo.',
    aliases: ['ImagePlaceholder', 'PhotoSlot', 'NoImage', 'Fallback', 'image-slot'],
    features: ['F011'],
    props: ['label'],
    states: ['landscape', 'square'],
    reusable: true,
    storyId: 'primitives-structure--image-placeholder',
  },
  {
    id: 'C012',
    name: 'EmptyState',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose:
      'Nothing-here panel. A Blueprint with a title, a clamped message and an optional action.',
    aliases: ['NoResults', 'Blank', 'ZeroState', 'Placeholder', 'NothingFound'],
    features: ['F012'],
    props: ['title', 'message', 'action'],
    states: ['plain', 'with-action', 'long-message'],
    reusable: true,
    storyId: 'primitives-states--empty',
  },
  {
    id: 'C013',
    name: 'ErrorState',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Something-broke panel, with an optional retry.',
    aliases: ['ErrorPanel', 'Failure', 'RetryState', 'LoadError'],
    features: ['F012'],
    props: ['title', 'message', 'action'],
    states: ['plain', 'with-retry'],
    reusable: true,
    storyId: 'primitives-states--error',
  },
  {
    id: 'C014',
    name: 'SkeletonLines',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Loading placeholder. Static bars, no shimmer — motion during loading is noise.',
    aliases: ['Skeleton', 'Loading', 'Shimmer', 'Placeholder', 'skeleton'],
    features: ['F012'],
    props: ['className'],
    states: ['default'],
    reusable: true,
    storyId: 'primitives-states--skeleton',
  },
  {
    id: 'C015',
    name: 'Stepper',
    source: 'apps/web/src/components/ui/primitives.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'Wizard progress bars. ⚠️ An out-of-range `current` fills every bar.',
    aliases: ['ProgressSteps', 'WizardProgress', 'StepIndicator', 'Progress'],
    features: ['F012', 'F037'],
    props: ['steps', 'current'],
    states: ['0', '1', '2', '3', 'out-of-range', 'negative'],
    reusable: true,
    storyId: 'primitives-states--stepper-positions',
  },
  {
    id: 'C016',
    name: 'Field',
    source: 'apps/web/src/components/forms/field.tsx',
    category: 'Forms',
    ownership: 'Shared',
    purpose: 'Label + control + error. The accessibility contract every form inherits.',
    aliases: ['FormField', 'FormGroup', 'LabelledInput', 'FormRow', 'field'],
    features: ['F013'],
    props: ['id', 'label', 'hint', 'error', 'children'],
    states: ['plain', 'hint', 'error', 'hint+error'],
    reusable: true,
    storyId: 'forms-field',
  },
  {
    id: 'C017',
    name: 'Input',
    source: 'apps/web/src/components/ui/input.tsx',
    category: 'Forms',
    ownership: 'Primitive',
    purpose: 'The .input class as a component. NEW at F013 — see finding D-B.',
    aliases: ['TextInput', 'TextField', 'input', 'FormControl'],
    features: ['F013'],
    props: ['every input attribute', 'className'],
    states: ['default', 'placeholder', 'hover', 'focus', 'disabled', 'aria-invalid'],
    reusable: true,
    storyId: 'forms-field--every-control',
  },
  {
    id: 'C018',
    name: 'Textarea',
    source: 'apps/web/src/components/ui/input.tsx',
    category: 'Forms',
    ownership: 'Primitive',
    purpose: 'textarea.input — its own stylesheet rule, so its own component.',
    aliases: ['TextArea', 'MultilineInput', 'Description'],
    features: ['F013'],
    props: ['every textarea attribute', 'className'],
    states: ['default', 'disabled', 'aria-invalid'],
    reusable: true,
    storyId: 'forms-field--every-control',
  },
  {
    id: 'C019',
    name: 'Select',
    source: 'apps/web/src/components/ui/input.tsx',
    category: 'Forms',
    ownership: 'Primitive',
    purpose: 'select.input, with the custom chevron. Not a Combobox — no filtering.',
    aliases: ['Dropdown', 'Picker', 'NativeSelect', 'select'],
    features: ['F013'],
    props: ['every select attribute', 'className'],
    states: ['default', 'disabled', 'aria-invalid'],
    reusable: true,
    storyId: 'forms-field--every-control',
  },
  {
    id: 'C020',
    name: 'CustomerHeader',
    source: 'apps/web/src/components/layout/customer-header.tsx',
    category: 'Layout',
    ownership: 'Shared',
    purpose: 'The buyer chrome — sticky 64px, wordmark, section nav, the two dealer doors.',
    aliases: [
      'PublicHeader',
      'SiteHeader',
      'Navbar',
      'TopBar',
      'BuyerHeader',
      'MarketplaceHeader',
      'customer-header',
    ],
    features: ['F073'],
    props: ['none — it reads usePathname()'],
    states: [
      'home (nothing current)',
      'cars',
      'dealers',
      'dealer portfolio (prefix match)',
      'saved',
      'mobile',
      'tablet',
    ],
    reusable: true,
    storyId: 'layout-customerheader',
  },
  {
    id: 'C021',
    name: 'CustomerFooter',
    source: 'apps/web/src/components/layout/customer-footer.tsx',
    category: 'Layout',
    ownership: 'Shared',
    purpose: 'The buyer footer, and the one line saying the dealer is the merchant.',
    aliases: ['PublicFooter', 'SiteFooter', 'Footer', 'customer-footer'],
    features: ['F073'],
    props: ['none'],
    states: ['default', 'mobile (nav wraps)'],
    reusable: true,
    storyId: 'layout-customerfooter',
  },
  {
    id: 'C021b',
    name: 'HeaderLink',
    source: 'apps/web/src/components/layout/customer-header.tsx',
    category: 'Layout',
    ownership: 'Feature-specific',
    purpose: 'One nav item, marked current in colour and in aria-current together.',
    aliases: ['NavLink', 'NavItem', 'HeaderNavLink', 'MenuLink'],
    features: ['F073'],
    props: ['href', 'active', 'children'],
    states: ['current', 'not current'],
    reusable: false,
    storyId: 'layout-customerheader',
  },
  {
    id: 'C022',
    name: 'AuthShell',
    source: 'apps/web/src/components/auth/auth-shell.tsx',
    category: 'Layout',
    ownership: 'Shared',
    purpose: 'The centred 560px column every sign-in and onboarding screen sits in.',
    aliases: ['AuthLayout', 'LoginShell', 'SignInShell', 'AuthPage', 'auth-shell'],
    features: ['F017', 'F018', 'F019', 'F037'],
    props: ['eyebrow', 'children', 'className'],
    states: ['default eyebrow', 'custom eyebrow'],
    reusable: true,
    storyId: 'layout-authshell',
  },
  {
    id: 'C023',
    name: 'AuthHeading',
    source: 'apps/web/src/components/auth/auth-shell.tsx',
    category: 'Layout',
    ownership: 'Shared',
    purpose: 'The 34px page title and the 15px line under it, on every auth screen.',
    aliases: ['LoginHeading', 'AuthTitle', 'SignInHeading', 'auth-heading'],
    features: ['F017', 'F018', 'F019', 'F037'],
    props: ['title', 'children'],
    states: ['with subtitle', 'without subtitle'],
    reusable: true,
    storyId: 'layout-authshell--heading-with-and-without-subtitle',
  },
  {
    id: 'C024',
    name: 'AdminNav',
    source: 'apps/web/src/components/admin/admin-nav.tsx',
    category: 'Admin',
    ownership: 'Shared',
    /**
     * No props at all: it reads `usePathname()` (coupling C-3), so the
     * pathname is the control — one story per route rather than a knob.
     */
    purpose: 'The admin sidebar nav. Reads the pathname; takes nothing.',
    aliases: ['AdminSidebar', 'AdminMenu', 'OpsNav', 'ConsoleNav', 'admin-nav'],
    features: ['F049'],
    props: [],
    states: [
      'dashboard',
      'listings',
      'dealers',
      'dealer detail',
      'payments',
      'configuration',
      'nothing current',
    ],
    reusable: true,
    storyId: 'admin-adminnav',
  },
  {
    id: 'C025',
    name: 'ConsoleNav',
    source: 'apps/web/src/components/dealer/console-nav.tsx',
    category: 'Console',
    ownership: 'Shared',
    /**
     * Items in, pathname read (coupling C-3). So `items` is a control and the
     * pathname is a parameter — one story per route rather than a knob.
     */
    purpose: 'The dealer console sidebar nav. Takes its items; reads the pathname for current.',
    aliases: ['DealerNav', 'DealerSidebar', 'ConsoleSidebar', 'DEALER_NAV', 'console-nav'],
    features: ['F047', 'R31'],
    props: ['items'],
    states: [
      'dashboard',
      'inventory',
      'editing a vehicle',
      'billing',
      'profile',
      'nothing current',
      'landed routes only',
    ],
    reusable: true,
    storyId: 'dealer-consolenav',
  },
  {
    id: 'C026',
    name: 'ConsoleTabBar',
    source: 'apps/web/src/components/dealer/console-nav.tsx',
    category: 'Console',
    ownership: 'Shared',
    /**
     * `md:hidden`, so it is invisible at a desktop viewport — the 375 and 768
     * viewport controls are the only way to see it at all.
     */
    purpose: 'The 56px bottom tab bar below 768. Five of the six nav items; none renders nothing.',
    aliases: ['DealerTabBar', 'BottomNav', 'MobileNav', 'TabBar', 'console-tab-bar'],
    features: ['F047', 'R31'],
    props: ['items'],
    states: ['five tabs', 'a tab current', 'nothing landed — renders null'],
    reusable: true,
    storyId: 'dealer-consolenav--tab-bar',
  },
  {
    id: 'C031',
    name: 'DirectoryFilters',
    source: 'apps/web/src/components/dealers/directory-filters.tsx',
    category: 'Dealer',
    ownership: 'Feature-specific',
    purpose:
      'The directory name search, its city toggle chips, and — with no district — the Select district button. Writes to the URL.',
    aliases: [
      'DealerFilters',
      'CityChips',
      'DealerSearch',
      'DirectorySearch',
      'directory-filters',
      'CityToggle',
    ],
    features: ['F085', 'R23'],
    props: ['cities', 'city', 'district', 'q', 'locations'],
    states: [
      'no district',
      'applied town, no district',
      'one town',
      'several towns',
      'searching',
      'town and search',
      'within a district',
      'no towns',
      'many towns',
    ],
    reusable: false,
    storyId: 'dealers-directoryfilters',
  },
  {
    id: 'C038',
    name: 'DirectoryCard',
    source: 'apps/web/src/components/dealers/dealer-card.tsx',
    category: 'Dealer',
    ownership: 'Shared',
    purpose: 'One dealership in the directory grid. The whole card is one link.',
    /*
     * Finding **D-6**, and the reason this field exists. The file is
     * `dealer-card.tsx`, the export is `DirectoryCard`, and `DealerCard` is a
     * contracts DTO — so a search for the obvious name has to land here rather
     * than returning a type and inviting a second card.
     */
    aliases: [
      'DealerCard',
      'dealer-card',
      'DealershipCard',
      'DirectoryTile',
      'DealerTile',
      'DealerListItem',
    ],
    features: ['F085'],
    props: ['dealer'],
    states: [
      'default',
      'no live cars',
      'one car',
      'sparse',
      'no tagline',
      'many services',
      'long brand name',
      'short and long name side by side',
      'service chips: one, two and three',
      'unverified',
      'with cover',
      'in the grid',
      'fullest',
      'same data twice',
    ],
    reusable: true,
    storyId: 'dealers-directorycard',
  },
  {
    id: 'C039',
    name: 'GoogleSignInButton',
    source: 'apps/web/src/components/auth/google-button.tsx',
    category: 'Layout',
    ownership: 'Shared',
    purpose: 'Continue with Google — an anchor, because OAuth needs a real navigation.',
    aliases: [
      'GoogleButton',
      'SignInWithGoogle',
      'OAuthButton',
      'ContinueWithGoogle',
      'google-button',
    ],
    features: ['F018'],
    props: ['href', 'label', 'disabled'],
    states: ['default', 'disabled', 'custom label'],
    reusable: true,
    storyId: 'layout-googlesigninbutton',
  },
  {
    id: 'C040',
    name: 'OnboardingWizard',
    source: 'apps/web/src/features/auth/onboarding-wizard.tsx',
    category: 'Forms',
    ownership: 'Feature-specific',
    purpose: 'Dealer onboarding end to end: the four-step frame and all four step bodies.',
    aliases: [
      'Onboarding',
      'OnboardingSteps',
      'DealerOnboarding',
      'SignupWizard',
      'RegistrationWizard',
      'Wizard',
      'onboarding-wizard',
    ],
    features: ['F037', 'F038', 'F039', 'F041', 'F042', 'F043'],
    /**
     * `cities` is gone rather than pending: the `cities` table went with it,
     * and step 2 types its city. `yardPhoto` takes its place in the list —
     * step 3 renders the hero photograph alongside the KYC checklist.
     */
    props: ['step', 'session', 'documents', 'dealer', 'completeness', 'yardPhoto'],
    states: [
      'Account',
      'Account (prefilled)',
      'Business',
      'Business (with description)',
      'Business (name taken)',
      'Changes requested',
      'Changes requested (multiline)',
      'Documents',
      'Documents (complete)',
      'Review',
    ],
    reusable: false,
    storyId: 'forms-onboardingwizard',
  },
  {
    id: 'C041',
    name: 'DocumentUploader',
    source: 'apps/web/src/features/auth/document-uploader.tsx',
    category: 'Forms',
    ownership: 'Feature-specific',
    purpose: 'One KYC document row: its state, and the presign/PUT/commit upload behind it.',
    aliases: [
      'KycUpload',
      'FileUpload',
      'Uploader',
      'DocumentRow',
      'DocUpload',
      'document-uploader',
    ],
    features: ['F041'],
    props: ['document'],
    states: ['required', 'uploading', 'deleting', 'in review', 'verified', 'rejected'],
    reusable: false,
    storyId: 'forms-documentuploader',
  },
  {
    id: 'C041b',
    name: 'YardPhotoUploader',
    source: 'apps/web/src/features/auth/yard-photo-uploader.tsx',
    category: 'Forms',
    ownership: 'Feature-specific',
    purpose: 'The dealership hero image: presign/PUT/commit, a preview, replace and delete.',
    aliases: [
      'YardPhoto',
      'CoverPhotoUploader',
      'HeroImageUploader',
      'BannerUploader',
      'PhotoUploader',
      'ImageUpload',
      'yard-photo-uploader',
    ],
    features: ['F041'],
    props: ['photo'],
    states: ['empty', 'uploaded', 'uploading', 'deleting', 'error'],
    reusable: false,
    storyId: 'forms-yardphotouploader',
  },
  {
    id: 'C043',
    name: 'SignOutButton',
    source: 'apps/web/src/features/auth/sign-out.tsx',
    category: 'Layout',
    ownership: 'Feature-specific',
    purpose: 'Ends the session — a POST form, never a link.',
    aliases: ['LogoutButton', 'SignOut', 'Logout', 'sign-out'],
    features: ['F020'],
    props: ['scope', 'className'],
    states: ['dealer scope', 'admin scope'],
    reusable: false,
    storyId: 'layout-signoutbutton',
  },
  {
    id: 'C044',
    name: 'DealerProfileForm',
    source: 'apps/web/src/features/dealer/profile-form.tsx',
    category: 'Console',
    ownership: 'Feature-specific',
    purpose: "The dealership's own record after onboarding — C1/C2, one PATCH.",
    aliases: [
      'ProfileForm',
      'DealerProfile',
      'Dealer settings',
      'Business details',
      'profile-form',
      'EditProfile',
    ],
    features: ['F046'],
    props: ['dealer'],
    states: ['populated', 'sparse', 'saved', 'field refusal', 'server error', 'saving'],
    reusable: false,
    storyId: 'dealer-dealerprofileform',
  },
  {
    id: 'C062',
    name: 'DealerAdminActions',
    source: 'apps/web/src/features/admin/dealer-actions.tsx',
    category: 'Admin',
    ownership: 'Feature-specific',
    purpose:
      'Approve, request changes, reject or suspend a dealership. The API says which is offered, not this.',
    aliases: [
      'DealerActions',
      'AdminDealerActions',
      'ApproveDealer',
      'SuspendDealer',
      'dealer-actions',
    ],
    features: ['F045'],
    props: ['dealer'],
    states: [
      'pending ready',
      'pending unverified',
      'both refusals',
      'active',
      'suspended',
      'draft',
      'in flight',
      'server error',
    ],
    reusable: false,
    storyId: 'admin-dealeradminactions',
  },
  {
    id: 'C062c',
    name: 'DealerProfileEditor',
    source: 'apps/web/src/features/admin/dealer-profile-editor.tsx',
    category: 'Admin',
    ownership: 'Feature-specific',
    purpose:
      "The dealership's own answers on the review screen — read by default, editable in place.",
    aliases: [
      'DealerEditor',
      'AdminDealerEdit',
      'BusinessCard',
      'EditDealer',
      'DealerBusinessDetails',
      'dealer-profile-editor',
    ],
    features: ['F045', 'R32'],
    props: ['dealer'],
    states: ['reading', 'with gaps', 'editing', 'read-only seat', 'saving', 'server refusal'],
    reusable: false,
    storyId: 'admin-dealerprofileeditor',
  },
  {
    id: 'C062d',
    name: 'ProfileChangeReview',
    source: 'apps/web/src/features/admin/profile-change-review.tsx',
    category: 'Admin',
    ownership: 'Feature-specific',
    /**
     * The gate on the only free text a dealer writes that a buyer reads.
     * Renders only when something is waiting — `profileChange` is PENDING-only.
     */
    purpose: "A dealer's proposed tagline and services, old beside new, with publish and refuse.",
    aliases: [
      'ProfileEditReview',
      'TaglineReview',
      'PendingProfileChange',
      'DealerEditApproval',
      'profile-change-review',
    ],
    features: ['R34'],
    props: ['change'],
    states: [
      'both fields changed',
      'phone number in the tagline',
      'services only',
      'tagline only',
      'nothing live to compare against',
      'refusing',
      'already decided',
      'deciding',
    ],
    reusable: false,
    storyId: 'admin-profilechangereview',
  },
  {
    id: 'C062b',
    name: 'DocumentReview',
    source: 'apps/web/src/features/admin/document-review.tsx',
    category: 'Admin',
    ownership: 'Feature-specific',
    purpose: 'The KYC checklist with a verdict on each row — verify, or reject with a reason.',
    aliases: [
      'KycReview',
      'DocumentVerification',
      'VerifyDocument',
      'RejectDocument',
      'AdminDocuments',
      'document-review',
    ],
    features: ['F044'],
    props: ['documents'],
    states: ['awaiting decision', 'verified', 'rejected', 'not uploaded', 'rejecting', 'in flight'],
    reusable: false,
    storyId: 'admin-documentreview',
  },
  {
    id: 'C066',
    name: 'Table',
    source: 'apps/web/src/components/ui/table.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose:
      'The .table class as a component, scroll container included. NEW at F045 — finding D-B.',
    aliases: ['DataTable', 'Grid', 'Rows', 'table', 'Listing table', 'TableColumn'],
    features: ['F045'],
    props: ['columns', 'caption', 'containerClassName', 'children'],
    states: ['many rows', 'single row', 'overflowing', 'no rows'],
    reusable: true,
    storyId: 'primitives-table',
  },
  {
    id: 'C067',
    name: 'NumericCell',
    source: 'apps/web/src/components/ui/table.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'A td with tabular-nums, so digits line up down a column (§4.2).',
    aliases: ['TableCell', 'TnumCell', 'NumberCell', 'td'],
    features: ['F045'],
    props: ['every td attribute', 'className'],
    states: ['count', 'balance', 'date'],
    reusable: true,
    storyId: 'primitives-table--default',
  },
  {
    id: 'C068',
    name: 'LocationCard',
    source: 'apps/web/src/components/dealers/location-card.tsx',
    category: 'Dealer',
    ownership: 'Feature-specific',
    purpose: "The portfolio's map of the yard, and the button that opens it in Google Maps.",
    aliases: [
      'MapCard',
      'DealerMap',
      'DirectionsCard',
      'location-card',
      'GetDirections',
      'YardMap',
      'PortfolioMap',
    ],
    features: ['F086'],
    props: ['address', 'brandName'],
    /*
     * Five. The first two are the map Google returns — the place card, with the
     * yard's name, rating and directions in the frame, against the bare pin a
     * link that named no place gets. The middle two are the point of the
     * component: the map and the button are independent, because a share link
     * carries neither until it is followed and following it is best-effort.
     */
    states: ['place card', 'pin only', 'directions only', 'map only', 'neither'],
    reusable: false,
    storyId: 'dealers-locationcard',
  },
  {
    id: 'C069',
    name: 'LocationSelector',
    source: 'apps/web/src/components/layout/location-selector.tsx',
    category: 'Layout',
    ownership: 'Feature-specific',
    purpose:
      "The header's district trigger. Reads 'Select district' until one is chosen (R23); the dialog is DistrictPicker (C071).",
    aliases: [
      'CitySelector',
      'DistrictSelector',
      'LocationPicker',
      'location-selector',
      'CityDropdown',
      'PlacePicker',
      'HeaderLocation',
      'LocationDialog',
      'StateDistrictPicker',
      'DistrictBrowser',
      'CityDistrictModal',
    ],
    features: ['F085', 'F086', 'R23'],
    props: ['locations'],
    states: [
      'no district chosen',
      'one chosen',
      'many states',
      'many districts',
      'searching',
      'state filtered',
      'no state recorded',
      'no districts',
    ],
    reusable: false,
    storyId: 'layout-locationselector',
  },
  {
    id: 'C071',
    name: 'DistrictPicker',
    source: 'apps/web/src/components/layout/district-picker.tsx',
    category: 'Layout',
    ownership: 'Shared',
    purpose:
      'The district dialog and the one rule for applying a district. NEW at R23, when the directory became a second opener.',
    aliases: [
      'LocationDialog',
      'DistrictDialog',
      'StateDistrictPicker',
      'district-picker',
      'useDistrictSelection',
      'DistrictBrowser',
      'CityDistrictModal',
      'LocationPicker',
    ],
    features: ['R23'],
    props: ['locations', 'children'],
    states: [
      'header trigger',
      'directory trigger',
      'one chosen',
      'many states',
      'searching',
      'state filtered',
      'no state recorded',
      'no districts',
    ],
    reusable: true,
    storyId: 'layout-districtpicker',
  },
  {
    id: 'C070',
    name: 'Dialog',
    source: 'apps/web/src/components/ui/dialog.tsx',
    category: 'Primitives',
    ownership: 'Primitive',
    purpose: 'DESIGN-SPEC §2.14. NEW at R22 — finding D-C: the .dialog CSS had zero consumers.',
    aliases: [
      'Modal',
      'Overlay',
      'Popup',
      'AlertDialog',
      'ConfirmDialog',
      'dialog',
      'dialog-backdrop',
      'Sheet',
      'Lightbox',
    ],
    features: ['R22'],
    props: [
      'open',
      'onOpenChange',
      'trigger',
      'title',
      'description',
      'closeLabel',
      'className',
      'contentClassName',
      'header',
      'footer',
      'children',
    ],
    states: ['default 440px', 'with description', 'wide + scrolling', 'no footer'],
    reusable: true,
    storyId: 'primitives-dialog',
  },
];

/** Case-insensitive search across name, aliases, purpose and category. */
export function findComponent(query: string): RegistryEntry[] {
  const needle = query.trim().toLowerCase();
  if (needle === '') return registry;

  return registry.filter((entry) =>
    [entry.name, entry.purpose, entry.category, ...entry.aliases]
      .join(' ')
      .toLowerCase()
      .includes(needle),
  );
}
